Sergiotestlana
SergeiDemyanenko/PlatformaticaQA_02 pull request #116
Opened 2021-05-13 14:46 UTC by Penny-Hofstadter

TestReview

2021-05-13 15:43 UTC, ArinaJur approved these changes
Поздравляю с первым PR! В следующем PR (test refactoring) можно обратить внимание на лишние пробелы в начале и в конце теста (удалить строки 13-16, 38, 39, 45-47 ). И и я рекомендую добавить Assert на какой нибудь текст при каждой навигации, чтобы подтверждать, что навигация работает правильно). Если нужна помощь с asserts, пишите.

2021-05-14 06:12 UTC, SergeiKuznetsov requested changes
Уберите избыточные пустые строки и приведите в порядок отступы. ))

2021-05-14 06:14 UTC, SergeiKuznetsov commented
> так же нужно удалить лишние 4 пробела в строках 31, 32 перед словом driver. 

Точнее наоборот. В этих строках отступы нормальные, а в остальных надо добавить пробелов чтобы выровнять.

2021-05-14 17:22 UTC, Penny-Hofstadter commented
> Уберите избыточные пустые строки и приведите в порядок отступы. ))

Done please check.

2021-05-14 17:23 UTC, Penny-Hofstadter commented
> > так же нужно удалить лишние 4 пробела в строках 31, 32 перед словом driver.
> 
> Точнее наоборот. В этих строках отступы нормальные, а в остальных надо добавить пробелов чтобы выровнять.

Code reformated.

2021-05-14 21:45 UTC, SergeiKuznetsov commented
Уже намного лучше!
Ещё можно убрать лишнюю пустую строку в методе afterTest
И добавить перенос строки в конце, там где GitHub показывает проблему 
![image](https://user-images.githubusercontent.com/13728212/118334698-f27f0d80-b4c2-11eb-94ae-f3829a7f5147.png)

2021-05-14 21:46 UTC, SergeiKuznetsov approved these changes

2021-05-14 21:48 UTC, SergeiKuznetsov requested changes
Проблема с названиями методов

2021-05-14 21:50 UTC, SergeiKuznetsov commented
**Method names**
For the method, names should use a lower camel case.
Method name should start with a verb.
For example: get, is, create, etc.
Try to make the name simple and descriptive.
Use whole words instead of abbreviations.
All methods with @Test annotation shall start with the prefix test.
https://github.com/SergeiDemyanenko/PlatformaticaQA_02#readme

2021-05-21 02:47 UTC, SergeiKuznetsov approved these changes

2021-05-21 02:48 UTC, merged