ViktoriaK Test
SergeiDemyanenko/PlatformaticaQA_02 pull request #118
Opened 2021-05-13 19:50 UTC by viktorijakm

2021-05-14 00:52 UTC, Daria-Razzhigaeva commented on src/test/java/GroupBreakingBadJavaTest.java
> +    public void testViktoriaKPark() throws InterruptedException {
Вам не нужно использовать throws InterruptedException потому что Вы не используете слипы в своем тесте.

2021-05-14 00:54 UTC, Daria-Razzhigaeva commented on src/test/java/GroupBreakingBadJavaTest.java
> +        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS) ;
Вам нужно убрать первые 4 строчки Вашего теста, потому что они уже реализованы в классе до начала всех тестов. Соответственно если Вы их еще и дублируете в своем тесте, то в конце браузер не закрывается.

2021-05-14 02:19 UTC, viktorijakm commented on src/test/java/GroupBreakingBadJavaTest.java
> +        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS) ;
Я пробовала - но потом тест почему-то не идет,

2021-05-14 02:19 UTC, viktorijakm commented on src/test/java/GroupBreakingBadJavaTest.java
> +    public void testViktoriaKPark() throws InterruptedException {
Ясненько,хорошо.

2021-05-14 03:21 UTC, Daria-Razzhigaeva commented on src/test/java/GroupBreakingBadJavaTest.java
> +        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS) ;
Я проверяла, нормально все проходило если удалить именно Ваши первые 4 строки. Если не удалять тоже нормально сам тест проходил, но браузер не закрывался.

2021-05-14 03:44 UTC, viktorijakm commented on src/test/java/GroupBreakingBadJavaTest.java
> +        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS) ;
хорошо, спасибо- я посмотрю. 
мне изменения сдесь делать или в интэли,я как-то ещё не разобралась?

2021-05-14 04:48 UTC, viktorijakm commented on src/test/java/GroupBreakingBadJavaTest.java
> +        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS) ;
вроде сделала

2021-05-14 06:10 UTC, SergeiKuznetsov requested changes

2021-05-14 06:10 UTC, SergeiKuznetsov commented on src/test/java/GroupBreakingBadJavaTest.java
> +
```suggestion
```

2021-05-14 06:10 UTC, SergeiKuznetsov commented on src/test/java/GroupBreakingBadJavaTest.java
> +
Эта пустая строка лишняя

2021-05-14 06:10 UTC, SergeiKuznetsov commented on src/test/java/GroupBreakingBadJavaTest.java
> +
```suggestion
```

2021-05-14 06:10 UTC, SergeiKuznetsov commented on src/test/java/GroupBreakingBadJavaTest.java
> +
Зачем добавлять пустую строку здесь?

2021-05-15 01:37 UTC, SergeiKuznetsov approved these changes

2021-05-15 05:29 UTC, GalinaRuban commented on src/test/java/GroupBreakingBadJavaTest.java
> +        WebElement input = driver.findElement(
а зачем тут перенос строки после findElement( ? и далее по тесту тоже такое... 
WebElement moreButton = driver.findElement( By.id("anch_20")) Это нужно в одну строку писать...

2021-05-15 17:32 UTC, viktorijakm commented on src/test/java/GroupBreakingBadJavaTest.java
> +        WebElement input = driver.findElement(
не обязательно

2021-05-17 04:29 UTC, SergeiKuznetsov commented on src/test/java/GroupBreakingBadJavaTest.java
> +        WebElement input = driver.findElement(
> а зачем тут перенос строки после findElement(

 Длинные строки можно переносить чтобы легче читать

2021-05-18 20:43 UTC, GalinaRuban commented on src/test/java/GroupBreakingBadJavaTest.java
> +        WebElement input = driver.findElement(
А где тут длинная строка? Длинное - это все что не влазит сюда https://prnt.sc/13362vb, потому тут перенос не очень правильный, как по мне...

2021-05-18 20:45 UTC, GalinaRuban commented on src/test/java/GroupBreakingBadJavaTest.java
> +        WebElement input = driver.findElement(
> не обязательно

я запросила изменения и бех них нельзя будет смерджить. Обычно неплохо прислушиваться к замечаниям...

2021-05-18 20:58 UTC, GalinaRuban requested changes

2021-05-18 20:58 UTC, GalinaRuban commented on src/test/java/GroupBreakingBadJavaTest.java
> +                By.id("anch_20"));
перенос не нужен тут

2021-05-18 23:32 UTC, GalinaRuban commented on src/test/java/GroupBreakingBadJavaTest.java
> +                .xpath("/html/body/div[11]/div[3]/div/div[2]/div[1]/h1"));
xpath can be replaced to //div[2]/div[1]/h1 or //h1[@class="page-title"]. Even //h1 can work, because usually there is one h1 on the page

2021-05-20 04:55 UTC, viktorijakm commented on src/test/java/GroupBreakingBadJavaTest.java
> +                .xpath("/html/body/div[11]/div[3]/div/div[2]/div[1]/h1"));
that's the address that I copied, I can't just changed it

2021-05-20 20:11 UTC, SergeiKuznetsov requested changes
@viktorijakm я разрешил конфликт. Перед тем как править код у себя, обязательно обнови **свою** ветку, сделав Update Project... в IntelliJ!
(ну или обнови сложным путём, через меню Git — Pull...)

2021-05-20 20:12 UTC, guram21 approved these changes

2021-05-20 20:19 UTC, viktorijakm commented
> @viktorijakm я разрешил конфликт. Перед тем как править код у себя, обязательно обнови **свою** ветку, сделав Update Project... в IntelliJ!
> (ну или обнови сложным путём, через меню Git — Pull...)
хорошо, просто я уже вчера поправили и выпала опция merge и я как бы сделала, но я еще посмотрю, Спасибо

2021-05-20 20:22 UTC, SergeiKuznetsov commented
Добейся от Галины одобрения по её претензии) Иначе так и не сможешь интегрировать свой тест в проект.

2021-05-20 20:26 UTC, viktorijakm commented on src/test/java/GroupBreakingBadJavaTest.java
> +        WebElement input = driver.findElement(
как бы уже сделано и олько аппрув нужен :)))

2021-05-20 21:50 UTC, SergeiKuznetsov requested changes

2021-05-20 21:50 UTC, SergeiKuznetsov commented on src/test/java/GroupBreakingBadJavaTest.java
> +        element.clear();
А зачем править чужой тест?

2021-05-21 01:45 UTC, SergeiKuznetsov approved these changes

2021-05-21 01:57 UTC, GalinaRuban approved these changes

2021-05-21 02:30 UTC, merged

2021-05-21 03:17 UTC, viktorijakm commented
@SergeiKuznetsov а почему ты удалил ветвь? она не нужна больше?
И теперь мне просто Merge делать?