Ilya v
SergeiDemyanenko/PlatformaticaQA_02 pull request #124
Opened 2021-05-14 18:44 UTC by KypoHeko

My first pull request.

2021-05-14 21:40 UTC, SergeiKuznetsov requested changes
Непонятное использование пустых строк, и наоборот отсутствие их там где бы надо им быть.

Я бы ещё вынес определение 
`private WebDriver driver;`
в начало класса, перед методами.

2021-05-14 21:40 UTC, SergeiKuznetsov commented on src/test/java/IlyaVTest.java
> +
```suggestion
```

2021-05-14 21:40 UTC, SergeiKuznetsov commented on src/test/java/IlyaVTest.java
> +    @BeforeClass
```suggestion

    @BeforeClass
```

2021-05-14 21:40 UTC, SergeiKuznetsov commented on src/test/java/IlyaVTest.java
> +
```suggestion
```

2021-05-14 21:40 UTC, SergeiKuznetsov commented on src/test/java/IlyaVTest.java
> +
```suggestion
```

2021-05-15 10:21 UTC, KypoHeko commented on src/test/java/IlyaVTest.java
> +
Исправил.

2021-05-15 10:21 UTC, KypoHeko commented on src/test/java/IlyaVTest.java
> +    @BeforeClass
Исправил.

2021-05-15 10:21 UTC, KypoHeko commented on src/test/java/IlyaVTest.java
> +
Исправил.

2021-05-15 10:22 UTC, KypoHeko commented on src/test/java/IlyaVTest.java
> +
Исправил.

2021-05-15 10:22 UTC, KypoHeko commented
Внёс исправления и запушил в свою ветку.

2021-05-17 04:25 UTC, SergeiKuznetsov approved these changes

2021-05-17 04:25 UTC, SergeiKuznetsov commented on src/test/java/IlyaVTest.java
> +    private WebDriver driver;
```suggestion

    private WebDriver driver;
```

2021-05-19 23:42 UTC, SergeiDemyanenko approved these changes

2021-05-20 01:50 UTC, merged