Valerii sarukhanov
SergeiDemyanenko/PlatformaticaQA_02 pull request #127
Opened 2021-05-15 03:54 UTC by ValeriiSarukhanov

Delete my old class.

2021-05-15 04:02 UTC, SergeiKuznetsov requested changes
Зачем добавлять дополнительный класс без тестов? Удали его.

И у тебе нужно разрешить один конфликт в классе группы.

2021-05-15 04:16 UTC, ValeriiSarukhanov commented
Конфликт решил. 
Класс удалять не буду. Он мне нужен. 
Мы же учимся.

2021-05-15 04:19 UTC, SergeiKuznetsov commented
> Класс удалять не буду. Он мне нужен.
> Мы же учимся.

Ты легко можешь сохранить свой класс в отдельной ветке, а не мусорить в основной ветке проекта. 
Никто тебе не мешает локально хранить всё что угодно. В проекте он зачем нам?

2021-05-15 04:22 UTC, ValeriiSarukhanov commented
Хочу от него отнаследоваться.
Мы все пишем одно и тоже, когда могли создать класс Utility и наследоваться от него.

2021-05-15 04:32 UTC, SergeiKuznetsov commented
> Хочу от него отнаследоваться.
> Мы все пишем одно и тоже, когда могли создать класс Utility и наследоваться от него.

Мысль хорошая, но доведи её до логического конца и только потом предлагай в проект ))
Базовый класс наверное должен быть абстрактным.

2021-05-15 04:54 UTC, ValeriiSarukhanov commented
Спасибо за коментарий.
Кое-что изменил.
Готово к проверке.

2021-05-15 04:59 UTC, SergeiKuznetsov commented
Ну так отнаследуйся от него теперь. Нужен же пример использования?

2021-05-15 05:02 UTC, ValeriiSarukhanov commented
Это будет новый PR . Там в классе группы надо refactor делать.

2021-05-15 05:20 UTC, SergeiKuznetsov commented
Вот туда и спрячь пока класс. Всё равно для нового PR понадобится новая ветка.

2021-05-15 05:31 UTC, ValeriiSarukhanov commented
Как мы будем практиковаться, если ты не даёшь дополнительный класс создать? Уж если этот класс будет плохим или ещё что-то, то Сергей во вторник легко его удалит.

2021-05-16 01:37 UTC, Reorg-ksarukhanova approved these changes

2021-05-16 03:46 UTC, sergeonevdah approved these changes

2021-05-16 03:47 UTC, sergeonevdah approved these changes

2021-05-16 03:52 UTC, sergeonevdah approved these changes

2021-05-16 03:56 UTC, sergeonevdah commented
А чего ты тогда не сделал наследование в GroupBugBustersTest от Utility?
И тогда все лишнее в GroupBugBustersTest нужно будет убрать

2021-05-16 03:57 UTC, ValeriiSarukhanov commented
Разве можно делать добавление кода и рефактор в одно ПР?

2021-05-16 03:57 UTC, ValeriiSarukhanov commented
Сделаю ещё один ПР.

2021-05-16 04:09 UTC, Karishka1234 approved these changes

2021-05-16 04:09 UTC, merged