refactoring of the class GroupRunSuccess.java (extends Utility)
SergeiDemyanenko/PlatformaticaQA_02 pull request #130
Opened 2021-05-16 10:20 UTC by dmytrostepanenko

Оснаследовался от класса Utility

2021-05-16 12:28 UTC, ValeriiSarukhanov commented
Добавьте, пожалуйста слово "Test" в конце названия класса. Посмотрите названия других классов.

2021-05-17 05:01 UTC, dmytrostepanenko commented
@ValeriiSarukhanov Добавил. Благодарю!

2021-05-17 11:26 UTC, ValeriiSarukhanov approved these changes

2021-05-18 03:24 UTC, SergeiKuznetsov requested changes

2021-05-18 03:24 UTC, SergeiKuznetsov commented on src/test/java/GroupRunSuccessTest.java
> +       @Test
```suggestion
    @Test
```

2021-05-19 02:20 UTC, SergeiKuznetsov submitted a review, later dismissed

2021-05-19 02:23 UTC, SergeiKuznetsov approved these changes

2021-05-19 02:23 UTC, merged