First test
SergeiDemyanenko/PlatformaticaQA_02 pull request #141
Opened 2021-05-18 17:44 UTC by Olesia1983

First test on YouTube.com web site for review.

2021-05-18 23:33 UTC, GalinaRuban approved these changes

2021-05-19 19:13 UTC, korikuman reviewed
this is initial test format, right now everyone modifying their tests to get rid of @Before methods, inherit BaseTest class, and use those before methods from BaseTest.
Your code looks good but I'd reccomend to modify your test to use BaseTest class.

2021-05-19 19:31 UTC, 4stuntman4 approved these changes

2021-05-20 01:54 UTC, SergeiKuznetsov requested changes

2021-05-20 01:54 UTC, SergeiKuznetsov commented on src/test/java/OlesiaAbdullinaTest.java
> +}
```suggestion
}

```

2021-05-20 01:55 UTC, SergeiKuznetsov requested changes

2021-05-20 01:55 UTC, SergeiKuznetsov commented on src/test/java/OlesiaAbdullinaTest.java
> +    public void firstTest() {
```suggestion
    public void testOlesiaAbdullina() {
```

2021-05-20 01:56 UTC, SergeiKuznetsov approved these changes

2021-05-20 01:57 UTC, merged