Galina k test refactoring may 18th
SergeiDemyanenko/PlatformaticaQA_02 pull request #143
Opened 2021-05-19 06:03 UTC by GALINA-KUKLEVA

refactoring  HW may 18th

2021-05-19 14:46 UTC, GalinaRuban commented on src/test/java/GalinaKTest.java
> +    public void testGalinaK() throws InterruptedException {
if there is no sleep in the test throws InterruptedException is not needed.

2021-05-19 18:06 UTC, SergeiDemyanenko requested changes
Зачем вы BaseTest.java отредактировали?

Если я что-то и изменила, то случайно. Но Ирина сегодня на практике изменила мой тест. У неё он прошел на её компьютере. А у меня не проходит с той же ошибкой.

2021-05-19 18:15 UTC, GALINA-KUKLEVA commented on src/test/java/GalinaKTest.java
> +    public void testGalinaK() throws InterruptedException {
Thank you! I added it just in case.

2021-05-20 02:17 UTC, SergeiKuznetsov commented on src/test/java/GalinaKTest.java
> +    public void testGalinaK() throws InterruptedException {
@GALINA-KUKLEVA надо удалить `throws InterruptedException` если не используется

2021-05-20 02:23 UTC, SergeiKuznetsov commented
>> Зачем вы BaseTest.java отредактировали?
> 
> Если я что-то и изменила, то случайно. Но Ирина сегодня на практике изменила мой тест. У неё он прошел на её компьютере. А у меня не проходит с той же ошибкой.

@GALINA-KUKLEVA вопрос был не в том, **как** вы поменяли BaseTest, а **зачем** вы его поменяли. Подразумавается что просят удалить его модификацию из своего запроса.

Я добавил коммит отмены этой правки.

2021-05-20 13:46 UTC, closed without merging