IrinaBnd_codeRefactoring
SergeiDemyanenko/PlatformaticaQA_02 pull request #153
Opened 2021-05-19 21:22 UTC by Vitaninka

code Refactoring in two tests

2021-05-19 22:37 UTC, MariaMoroz commented on src/test/java/IrinaBTest.java
>      public void testIrinaB2() throws InterruptedException {
Для чего у Вас "throws InterruptedException"?

2021-05-19 23:46 UTC, SergeiDemyanenko requested changes
В PR исправлен один класс и добавлен другой, для 2х изменений нужно 2 отдельных PR

2021-05-19 23:49 UTC, ArinaJur commented on src/test/java/WedReviewIZTest.java
> +    public void reviewTest() throws InterruptedException{
Если этот код попал в PR, то нужно удалить throws InterruptedException и лишние 20 и 23 строки

2021-05-20 00:52 UTC, Vitaninka commented on src/test/java/IrinaBTest.java
>      public void testIrinaB2() throws InterruptedException {
It doesn't belong there cause it belongs to the class I was dead sure deleted it from Platformatica.

2021-05-20 00:55 UTC, Vitaninka commented on src/test/java/WedReviewIZTest.java
> +    public void reviewTest() throws InterruptedException{
Ирин, извини!n думала удалила весь класс, оказалось нет, и он он ушёл вместе с PR

2021-05-20 02:33 UTC, SergeiKuznetsov requested changes

2021-05-20 02:33 UTC, SergeiKuznetsov commented on src/test/java/WedReviewIZTest.java
> +    public void reviewTest() throws InterruptedException{
@Vitaninka Объяснить как это исправить или сама справишься?

2021-05-20 02:37 UTC, Vitaninka commented on src/test/java/WedReviewIZTest.java
> +    public void reviewTest() throws InterruptedException{
@SergeiKuznetsov Пытаюсь сейчас... Я бы хотела удалить вот этот целый класс, но лучше помоги, плиз!:)

2021-05-20 03:27 UTC, SergeiKuznetsov requested changes

2021-05-20 03:27 UTC, SergeiKuznetsov commented on src/test/java/IrinaBTest.java
> +    public void testIrinaB2() throws {
```suggestion
    public void testIrinaB2() {
```

2021-05-20 03:37 UTC, SergeiKuznetsov approved these changes

2021-05-20 03:41 UTC, SergeiKuznetsov commented on src/test/java/IrinaBTest.java
>      public void testIrinaB(){
```suggestion
    public void testIrinaB() {
```

2021-05-20 03:43 UTC, SergeiKuznetsov commented on src/test/java/IrinaBTest.java
>      public void testIrinaB(){
Мозолит глаза эта ошибка ))

2021-05-20 19:42 UTC, ArinaJur approved these changes
Good job!

2021-05-20 22:40 UTC, merged