Refactoring: extends class BaseTest: deleting Before, After annotation
SergeiDemyanenko/PlatformaticaQA_02 pull request #154
Opened 2021-05-19 21:48 UTC by mishinaolia

…ns; substitution field driver with getDreiver

2021-05-20 03:57 UTC, SergeiKuznetsov requested changes

2021-05-20 03:57 UTC, SergeiKuznetsov commented on src/test/java/OlgaMishinaTest.java
> +  public void test() throws InterruptedException, SQLException {
Где эти trows используются? Наверное лучше удалить их.
И удалить все лишние import

2021-05-20 19:52 UTC, mishinaolia commented on src/test/java/OlgaMishinaTest.java
> +  public void test() throws InterruptedException, SQLException {
fixed

2021-05-20 23:32 UTC, SergeiKuznetsov commented
Пустая строка в конце файла важна, не надо её удалять. Видишь как теперь GitHub [ругается](https://github.com/SergeiDemyanenko/PlatformaticaQA_02/pull/154/commits/4de854ad1a599b921951de0cf589d65561338535) на её отсутсвие? Точнее сказать он ругается на отсутствие переноса строки. 
![image](https://user-images.githubusercontent.com/13728212/119061063-476dc880-b988-11eb-82f1-2eb7259b415e.png)

В конце самой последней строки кода всегда добавляй символ переноса строки (жми Enter)
Это важно.

2021-05-20 23:39 UTC, SergeiKuznetsov commented
Не надо писать слишком длинную тему сообщения. В заголовке описываем кратко суть, а в дальше уже описываем подробно сколько душе угодно.

Если пытаться воткнуть слишком много мыслей в заголовок, то гитхаб его обрежет и остаток строки перенесёт из темы в тело сообщения запроса.

![image](https://user-images.githubusercontent.com/13728212/119061537-7173ba80-b989-11eb-8a8d-abef82a63093.png)

2021-05-20 23:40 UTC, SergeiKuznetsov commented
Вот так запрос становится осмысленней и понятней для рецензентов.
![image](https://user-images.githubusercontent.com/13728212/119061786-070f4a00-b98a-11eb-9013-8c646c7dd6a0.png)

2021-05-21 01:09 UTC, mishinaolia commented
ok, thanks. I got it.

2021-05-21 02:25 UTC, SergeiKuznetsov approved these changes

2021-05-21 04:16 UTC, guram21 approved these changes

2021-05-21 04:24 UTC, merged