Ilya v  branch
SergeiDemyanenko/PlatformaticaQA_02 pull request #169
Opened 2021-05-20 15:35 UTC by KypoHeko

Refactored

2021-05-20 19:15 UTC, SergeiKuznetsov approved these changes
Сообщение запроса на слияние, как и сообщение коммита, предназначено для того, чтобы там описали суть предлагаемого изменения, а не для того, чтобы вставить туда бессмысленный текст. 
:) 
И это именно предложение что-то изменить, а не свершившийся факт. Поэтому уместнее повелительное наклонение (императив)

2021-05-21 00:17 UTC, AlekseiMaslo requested changes

2021-05-21 00:17 UTC, AlekseiMaslo commented on src/test/java/IlyaVTest.java
>      public void test() throws InterruptedException {
Так как мы уже не используем обычные Thread.sleep, то throws InterruptedException больше можно не использовать.

2021-05-21 03:43 UTC, SergeiKuznetsov requested changes

2021-05-21 03:43 UTC, SergeiKuznetsov commented on src/test/java/IlyaVTest.java
>      public void test() throws InterruptedException {
```suggestion
    public void test() {
```

2021-05-21 04:25 UTC, KypoHeko commented on src/test/java/IlyaVTest.java
>      public void test() throws InterruptedException {
Удалил из 11 строки throws InterruptedException

2021-05-21 04:26 UTC, KypoHeko commented on src/test/java/IlyaVTest.java
>      public void test() throws InterruptedException {
Удалил из 11 строки throws InterruptedException

2021-05-21 06:54 UTC, SergeiDemyanenko approved these changes

2021-05-21 07:49 UTC, SergeiKuznetsov approved these changes

2021-05-21 07:50 UTC, SergeiKuznetsov commented on src/test/java/IlyaVTest.java
>      public void test() throws InterruptedException {
@AlekseiMaslo  закрой пожалуйста

2021-05-21 17:08 UTC, GalinaRuban approved these changes

2021-05-21 17:08 UTC, merged