Stas champion test1
SergeiDemyanenko/PlatformaticaQA_02 pull request #196
Opened 2021-05-23 04:57 UTC by Staschampion

change click button

2021-05-23 08:09 UTC, SergeiKuznetsov requested changes
Раз сделал наследование, то удали лишнее из класса

2021-05-24 04:16 UTC, Staschampion commented
last fix

2021-05-24 04:17 UTC, Staschampion commented
> Раз сделал наследование, то удали лишнее из класса

все исправил

2021-05-24 04:48 UTC, SergeiKuznetsov approved these changes

2021-05-24 05:54 UTC, guram21 approved these changes

2021-05-24 17:02 UTC, GalinaRuban approved these changes

2021-05-25 16:21 UTC, merged