Ponomid_Test_Entity_Parent_CreateNewRecord
SergeiDemyanenko/PlatformaticaQA_02 pull request #205
Opened 2021-05-24 22:45 UTC by ponomid

Created just first part of the test as Irina told on Review(based on my own US and TC)

2021-05-24 22:59 UTC, Burdishka requested changes

2021-05-24 22:59 UTC, Burdishka commented on src/test/java/EntityParentTest.java
> +                .click();
такие локаторы не стабильны

2021-05-24 22:59 UTC, Burdishka commented on src/test/java/EntityParentTest.java
> +        getDriver().get("https://ref2.eteam.work/index.php?action=action_list&entity_id=57&mod=2");
не надо так делать переход на entity Parent
locator.click()

2021-05-26 03:59 UTC, ponomid commented on src/test/java/EntityParentTest.java
> +        getDriver().get("https://ref2.eteam.work/index.php?action=action_list&entity_id=57&mod=2");
Will fix tomorrow

2021-05-27 22:13 UTC, closed without merging