Af 05/24
SergeiDemyanenko/PlatformaticaQA_02 pull request #207
Opened 2021-05-25 04:55 UTC by BELOVEZHIE

2021-05-25 14:21 UTC, Burdishka requested changes
Ты работаешь уже не посредственно над Entity, по этому название PR должно быть говоряеще, и так же нет прикрепленных юзер стори над которыми ты работаешь.
Два теста. Второй полностью на 95% повторяет первый. Сделай зависимось у второго теста @Test(dependsOnMethods = "название первого теста") и просто продолжай с того места где закончился первый тест.

так же без юзер стори не понятно что должен проверять тест. Нету Assert. Если их не собираешься использовать можешь оставить комментарий //assertion в том месте где это выполняется

не надо дублировать код, а у тебя это практически 50%

2021-05-25 14:21 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        elementForMouse.click();
разве обычным кликом нельзя обойтись?

2021-05-25 14:21 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        saveButtonClick.click();
есть реализованый метод jsClick в TestUtils

2021-05-25 14:21 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        datetimeField.click();
тут в принципе не обязательно создавать переменные Webelement, по их XPath понятно что за поля

2021-05-25 14:21 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        datetimeField.click();
если ты их не используешь два раза в классе как минимум или нужно дать знать что это за локатор

2021-05-25 14:21 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        listButton.click();
над локатором надо поработать, по линкам искать локатор так себе

2021-05-25 14:21 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        restoreDraft.click();
поработай на локаторами

2021-05-26 01:15 UTC, BELOVEZHIE commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        getDriver().manage().window().maximize();
Got it.

2021-05-26 01:16 UTC, BELOVEZHIE commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        pushDelete.click();
Got it.

2021-05-26 01:27 UTC, BELOVEZHIE commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        WebElement elementForMouse = getDriver().findElement(By.xpath("//*[@id=\"menu-list-parent\"]/ul/li[10]/a/p"));
It fits!!!

2021-05-26 01:32 UTC, BELOVEZHIE commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        elementForMouse.click();
Привет. Нет. не получается, т.к. слева всплывающее поле с Entities и Board лежит ниже, за границами страницы.

2021-05-26 01:39 UTC, BELOVEZHIE commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        saveButtonClick.click();
Got it!

2021-05-26 01:40 UTC, BELOVEZHIE commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        datetimeField.click();
Ok. Helpful.

2021-05-26 01:43 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        elementForMouse.click();
а я вот попробовал у тебя в твоей ветке поменять локатор на тот который я выше дал и нажимает локально на компьютере

2021-05-26 01:46 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        elementForMouse.click();
ну и по поводу Thread.sleep() - без них разве не проходит тест? если ты ставишь паузу 4 секунды, в нескольких местах. Их надо ставить только тогда когда без них никак, но в будущем вы вообще от них должны избавиться

2021-05-26 01:48 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        elementForMouse.click();
и название класса должно быть EntityBoardTest, если такой класс уже существует так как кто-то делает тесты связанные с этой entity, то нужно назови немного по-другому, но потом нужно перенести твои тесты в EntityBoardTest

2021-05-26 01:49 UTC, BELOVEZHIE commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        elementForMouse.click();
Ok. Попробую. Слипы убрал уже. Видимо из-за за двоения implicit давало сбои. Не видел реализацию в ProjectUtils.

2021-05-26 01:51 UTC, BELOVEZHIE commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        elementForMouse.click();
Попробую еще по Action. Но жалко уже убирать, я его в отдельный метод вывел уже))))

2021-05-26 02:32 UTC, Burdishka commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        elementForMouse.click();
у меня получилось обычным кликом, если нет - обычный клик не реаботает в этом случае, то уже есть реализован метод scrollClick в TestUtils - используй его.

2021-05-26 02:44 UTC, BELOVEZHIE commented on src/test/java/BoardTDeleteAndMoveTests.java
> +        elementForMouse.click();
Ok. Попробую и дам знать.

2021-05-26 23:46 UTC, Burdishka commented
у тебя в названии класса ошибка - s вконце лишняя
ты работаешь с классом EntityBoardTest, но такой уже класс создали и вроде даже тесты как у тебя про удаление. Вы случайно не дублируете друг друга??

2021-05-27 16:07 UTC, closed without merging

2021-05-27 16:08 UTC, BELOVEZHIE commented
Broken