TC_004.02_Java | Entity>Board: Edit created record
SergeiDemyanenko/PlatformaticaQA_02 pull request #213
Opened 2021-05-26 05:31 UTC by NYerlan

2021-05-26 05:34 UTC, NYerlan commented
https://trello.com/c/RcuwzmIJ/12-tc00402java-entityboard-edit-created-record

2021-05-26 12:58 UTC, Burdishka requested changes

2021-05-26 12:58 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().get("https://ref2.eteam.work/index.php?action=action_create&entity_id=31");
На Entity нужно кликать а не вбивать url что бы загрузилась страничка этой entity

Таким образомты пропускаешь два шага:
* не нажимаешь на entity
* не нажимаешь на кнопку create record

2021-05-26 12:58 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().get("https://ref2.eteam.work/index.php?action=action_list&entity_id=31&mod=2");
используй locator.click() а не url для перехода

2021-05-26 12:58 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            WebElement textField = getDriver().findElement(By.xpath("//textarea[@id='text']"));
дублирование кода, у тебя уже есть этот xpath в 17 строке, создай там переменную и тут уже ее вызывай

2021-05-26 12:58 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            WebElement intField = getDriver().findElement(By.xpath("//input[@id='int']"));
дублирование кода, у тебя уже есть этот xpath в 18 строке, создай там переменную и тут уже ее вызывай

2021-05-26 12:58 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            TestUtils.scrollClick(getDriver(),saveButtonEdit);
уже создан Webelement кнопка у тебя в 19 строке, тут не надо создавать такую же с другим названием, просто TestUtils.scrollClick(getDriver(),saveButton);

2021-05-26 12:58 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().findElement(By.xpath("//li//a[@class='nav-link ']/i[@class='material-icons']")).click();
если не будешь изначально делать переход по url то тогда у тебя после сохранения будет все нормально отображаться, делай так как мануально, ты ведь мануально не пишешь руками url?

2021-05-26 15:10 UTC, NYerlan commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().get("https://ref2.eteam.work/index.php?action=action_list&entity_id=31&mod=2");
Здесь начало моего теста по ТС, поэтому переход по url  на определенную страницу - начало теста

2021-05-26 15:10 UTC, NYerlan commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().get("https://ref2.eteam.work/index.php?action=action_create&entity_id=31");
Мой тест кейс - редактирование записи. Поэтому 1ая часть кода  (создание записи) - временный  код, потом будет удален когда другой тестер создаст этот тест. Поэтому здесь я использовал максимально короткий путь с использованием url и прямым переходом на create record.

2021-05-26 15:10 UTC, NYerlan commented on src/test/java/EntityBoardEditRecordTest.java
> +            WebElement textField = getDriver().findElement(By.xpath("//textarea[@id='text']"));
1ая часть кода  (строки 16-21) - временный  код, потом будут удалены

2021-05-26 15:10 UTC, NYerlan commented on src/test/java/EntityBoardEditRecordTest.java
> +            WebElement intField = getDriver().findElement(By.xpath("//input[@id='int']"));
1ая часть кода  (строки 16-21) - временный  код, потом будут удалены

2021-05-26 15:10 UTC, NYerlan commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().findElement(By.xpath("//li//a[@class='nav-link ']/i[@class='material-icons']")).click();
Здесь начинается проверка, поэтому начало с определенной страницы сайта, соглсно ТС

2021-05-26 15:22 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().get("https://ref2.eteam.work/index.php?action=action_create&entity_id=31");
переход по прямым линкам не надо делать, используй локаторы, ты имитируешь мануальное тестирование а не пытаешься упростить себе задачу

2021-05-26 15:22 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().get("https://ref2.eteam.work/index.php?action=action_list&entity_id=31&mod=2");
без url

2021-05-26 15:23 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            WebElement textField = getDriver().findElement(By.xpath("//textarea[@id='text']"));
не надо дублировать код, ты уже можешь укоротить код, даже если что-то временно

2021-05-26 15:23 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            WebElement intField = getDriver().findElement(By.xpath("//input[@id='int']"));
не надо дублировать код, ты уже можешь укоротить код, даже если что-то временно

2021-05-26 15:23 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            TestUtils.scrollClick(getDriver(),saveButtonEdit);
не надо дублировать код, ты уже можешь укоротить код, даже если что-то временно

2021-05-26 15:25 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().findElement(By.xpath("//li//a[@class='nav-link ']/i[@class='material-icons']")).click();
автоматизированый тест это имитация мануального тестирования с помощью строчек кода, мы должны делать все как руками. Мы тестируем для того что бы убедиться что все работает как должно работать по требованиям а не для того что бы укоротить или упростить себе задачу

2021-05-26 15:27 UTC, Burdishka commented
Можешь написать комментарий, но лучше всего взять юзер стори с созданием записи и сделать как надо или возьми под руки товарища и вместе сделайте, пока юзер стори есть достаточно и они не заняты, если у тебя есть время и желание это сделать - сделай. Я пишу комментарии не для того что бы сделать хуже - только наоборот. Тяжело в учении - легко в бою!

2021-05-27 17:38 UTC, ArinaJur commented
> * testcreateRecordTest
> * testeditRecordTest
>   и поставить зависимость второго от первого
Студентам этого еще не объясняли. На уроке Сергея было официально разрешено дублировать код, писать дубликаты одного и того же теста, одной и той же user story, писать временные тесты. ПОка на проекте задача - начать писать тесты. Студенты очень много пока "не проходили".

2021-05-27 17:43 UTC, ArinaJur reviewed
Я бы заапрувила вам тест, учитывая, что вы все делаете так, как разрешено, и на том уровне, на котором было рассказано на уроках. НО у вас нет ни одной ссылки на задачи из Трелло - вы должны ставить в комментарий теста ссылки на задачи. Вот об этом говорилось много раз и я не могу аппрувнуть без ссылок на задачи в Трелло

2021-05-27 17:43 UTC, ArinaJur commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().get("https://ref2.eteam.work/index.php?action=action_create&entity_id=31");
Мы так делали на ревью, тк пока сложно искать некоторые локаторы. Тесты будут позже рефакториться

2021-05-27 17:43 UTC, ArinaJur commented on src/test/java/EntityBoardEditRecordTest.java
> +            WebElement textField = getDriver().findElement(By.xpath("//textarea[@id='text']"));
Дублирование кода было официально разрешено на уроке, тк это временная ситуация

2021-05-27 23:40 UTC, Burdishka commented on src/test/java/EntityBoardEditRecordTest.java
> +            getDriver().get("https://ref2.eteam.work/index.php?action=action_create&entity_id=31");
ок, я все понял

2021-05-27 23:40 UTC, Burdishka approved these changes

2021-05-28 00:56 UTC, SergeiKuznetsov commented
`Failed tests:   testEditCreatedRecord(EntityBoardEditRecordTest): no such element: Unable to locate element: {"method":"xpath","selector":"//textarea[@id='text']"}(..)`

2021-05-28 05:32 UTC, merged