AM entity placeholder create save
SergeiDemyanenko/PlatformaticaQA_02 pull request #225
Opened 2021-05-27 05:32 UTC by Mackedonsky

https://trello.com/c/hrt1YKjY/211-at040-entityplaceholder-create-a-new-record-and-save

2021-05-27 14:18 UTC, Burdishka requested changes

2021-05-27 14:18 UTC, Burdishka commented on src/test/java/EntityPlaceholderTest.java
> +        WebElement openDash = getDriver().findElement(By.xpath("//p[contains (text(), 'Placeholder')]"));
название локатора не имеет конкретики, XPath мне больше дает знать чем название локатора
предлагаю menuPlaceholder

2021-05-27 14:18 UTC, Burdishka commented on src/test/java/EntityPlaceholderTest.java
> +        ProjectUtils.start(getDriver());
сделай пустую разделительную строку после 14

2021-05-27 14:18 UTC, Burdishka commented on src/test/java/EntityPlaceholderTest.java
> +        WebElement user = getDriver().findElement(By.xpath("//span[contains (text(),  \"tester99@tester.test\")]"));
нет смысла создавать переменную user что бы потом только впихнуть его scrollClick()

2021-05-27 14:18 UTC, Burdishka commented on src/test/java/EntityPlaceholderTest.java
> +        WebElement user = getDriver().findElement(By.xpath("//span[contains (text(),  \"tester99@tester.test\")]"));
создаем либо для повторного использования либо мы очень хотим показать что это за локатор, но у тебя по XPath все понятно

2021-05-27 14:18 UTC, Burdishka commented on src/test/java/EntityPlaceholderTest.java
> +        TestUtils.jsClick(getDriver(), getDriver().findElement(By.id("pa-entity-form-save-btn")));
кнопку saveButton не нажимается обычным кликом? ок, а scrollClick()?
дело в том что jsClick() нужно использовать только в самых крайних случаях, он нажмет на кнопку даже если ее не будет видно, а мы имитируем работу пользователя

2021-05-27 14:18 UTC, Burdishka commented on src/test/java/EntityPlaceholderTest.java
> +        WebElement result = getDriver().findElement(By.xpath(placeholder));
после 31 добавь пустую строку

2021-05-27 14:18 UTC, Burdishka commented on src/test/java/EntityPlaceholderTest.java
> +
33 лишняя пустая строка

2021-05-28 01:44 UTC, Mackedonsky commented on src/test/java/EntityPlaceholderTest.java
> +        TestUtils.jsClick(getDriver(), getDriver().findElement(By.id("pa-entity-form-save-btn")));
В чем разница? В функции scrollClick() тоже используется js script же?

2021-05-28 01:55 UTC, Burdishka commented on src/test/java/EntityPlaceholderTest.java
> +        TestUtils.jsClick(getDriver(), getDriver().findElement(By.id("pa-entity-form-save-btn")));
в scrollClick() есть scroll(), это в принципе заменяет работу пользователя, скролит страничку но потом срабатывает обычный click(). Т.е. как бы мы видим что мы нажимаем. 

А вот jsClick() может нажать на елемент даже если его не видно на экране но он есть в DOM. А мы тестируем и имитируем работу пользователя, пользователь явно не нажимает джаваскриптом. Вот в этом есть разница.

2021-05-28 01:55 UTC, Mackedonsky commented on src/test/java/EntityPlaceholderTest.java
> +        TestUtils.jsClick(getDriver(), getDriver().findElement(By.id("pa-entity-form-save-btn")));
Failed tests:   testCreateNewRecord(EntityPlaceholderTest): element click intercepted: Element <button type="submit" id="pa-entity-form-save-btn" class="btn btn-warning" name="action_status" value="1">...</button> is not clickable at point (44, 787). Other element would receive the click: <p>...</p>(..)

тест падает, если использовать scrollClick()

2021-05-28 01:56 UTC, Burdishka approved these changes

2021-05-28 02:15 UTC, guram21 approved these changes

2021-05-28 02:15 UTC, merged