Board delete test
SergeiDemyanenko/PlatformaticaQA_02 pull request #229
Opened 2021-05-27 16:05 UTC by BELOVEZHIE

https://trello.com/c/jf2hAGpo/2-us002-entity-board-delete-existing-record

2021-05-27 16:18 UTC, Burdishka commented on src/test/java/EntityBoardTest2.java
> +
лишняя пустая строчка

2021-05-27 16:19 UTC, Burdishka commented on src/test/java/EntityBoardTest2.java
> +        WebElement recyclerBin = getDriver().findElement(By.xpath("//div[2]/div[1]/div/div/div"));
такой XPath не стабильный

2021-05-27 16:20 UTC, Burdishka commented on src/test/java/EntityBoardTest2.java
> +        new WebDriverWait(getDriver(), 15);
что делает этот стейтмент? это используется где-то?

2021-05-27 16:20 UTC, Burdishka commented on src/test/java/EntityBoardTest2.java
> +        new WebDriverWait(getDriver(), 5);
что делает этот стейтмент? это используется где-то?

2021-05-27 16:21 UTC, Burdishka commented on src/test/java/EntityBoardTest2.java
> +        login(getDriver());
есть метод start в ProjectUtils но его можно вызывать в начале теста

2021-05-27 16:24 UTC, Burdishka commented on src/test/java/EntityBoardTest2.java
> +        //click on recycler bin icon
комментарии в коде не допустимы, только в редких случая для пояснения
тут мы понимаем что происходят клики
зачем постоянно делать new WebDriverWait(getDriver(), 15) и не пользоваться этим?
в BaseTest есть driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

2021-05-27 16:29 UTC, BELOVEZHIE commented on src/test/java/EntityBoardTest2.java
> +        reset(getDriver());
Да, можно заменить на start()

2021-05-27 16:29 UTC, BELOVEZHIE commented on src/test/java/EntityBoardTest2.java
> +        reset(getDriver());
ok

2021-05-27 16:29 UTC, BELOVEZHIE commented on src/test/java/EntityBoardTest2.java
> +
ok

2021-05-27 16:29 UTC, BELOVEZHIE commented on src/test/java/EntityBoardTest2.java
> +        WebElement recyclerBin = getDriver().findElement(By.xpath("//div[2]/div[1]/div/div/div"));
ok

2021-05-27 16:30 UTC, BELOVEZHIE commented on src/test/java/EntityBoardTest2.java
> +        login(getDriver());
)

2021-05-27 16:31 UTC, BELOVEZHIE commented on src/test/java/EntityBoardTest2.java
> +        //click on recycler bin icon
Я понимаю, что он есть. Но он не всегда помогает. Часто тест падал из element not interactable.

2021-05-27 19:41 UTC, SergeiKuznetsov commented
Кто-то удалил User Story

2021-05-27 20:20 UTC, BELOVEZHIE commented
Да, случайно. Сори. Как восстановить не разобрался

On Thu, May 27, 2021 at 12:42 PM Sergey Kuznetsov ***@***.***>
wrote:

> Кто-то удалил User Story
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SergeiDemyanenko/PlatformaticaQA_02/pull/229#issuecomment-849891647>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APRQE4TGGYN5PGEIWERGB5TTP2OBDANCNFSM45UUEJ6Q>
> .
>

2021-05-28 00:28 UTC, SergeiKuznetsov commented
> Да, случайно. Сори. Как восстановить не разобрался

Для начала добавь в PR ссылки на карточки Test Case и Automation

2021-05-28 01:42 UTC, BELOVEZHIE commented
Я не могу прикрепить ссылку на карточку, т.к. случайно удалил её.

2021-05-28 02:04 UTC, MichaelMicrof requested changes

2021-05-28 02:04 UTC, MichaelMicrof commented on src/test/java/EntityBoardTest2.java
> +        new WebDriverWait(getDriver(), 15);
Зачем столько таймаутов? и почему на 15 сек? 5 более чем достаточно. К тому же мы используем implicitly.wait

2021-05-28 02:04 UTC, MichaelMicrof commented on src/test/java/EntityBoardTest2.java
> +        WebElement recordText = getDriver().findElement(By.xpath("//*[@id=\"kanban\"]/div/div[1]/main/div/div[2]"));
не стоит использовать такие локаторы, надо самому писать их, а не копировать автоматом

2021-05-28 02:04 UTC, MichaelMicrof commented on src/test/java/EntityBoardTest2.java
> +}
добавь строчку в конце

2021-05-30 01:12 UTC, closed without merging