Va kor/refactoring
SergeiDemyanenko/PlatformaticaQA_02 pull request #240
Opened 2021-05-28 08:40 UTC by Wis13

[Trello](https://trello.com/c/bKMydfYk/249-refactoring-or-improve-testutils)
Refactoring or improve TestUtils

2021-05-28 16:36 UTC, skhat requested changes

2021-05-28 19:59 UTC, Wis13 commented on src/test/java/EntityPlaceholderEditTest.java
> +//        getDriver().findElement(FIELD_PLACEHOLDER_DATE).click();
Сорри од долго не проходоил а пром прошел CI и я забыл поправить :)

2021-05-28 20:00 UTC, Wis13 commented on src/test/java/utils/TestUtils.java
> +
Ок

2021-05-28 22:50 UTC, SergeiKuznetsov requested changes
1.  Вадим, мне непонятно твоё желание вставить своё имя в тему PR. Для этого есть веские причины? Разве не достаточно что все коммиты подписываются нашими данными?  На своём компьютере ты имя прописал, теперь сделай то же самое в [профиле](https://www.notion.so/4aff35cd5e154b4b94ba149846ffab76#67a07e8e117f4addaaa0ef79cf47a107) на GitHub и остальных наших сайтах.
2. Не используй сложные глаголы. В заголовке принято писать в повелительном наклонии. Короче говоря, берём глагол в неопределённой форме и отбраcываем частицу **to**. Refactor, fix, add, delete, modify, improve... Такой стиль используется по-умолчанию везде в Git.
3. Поправь заголовок на более осмысленный. Например «Refactor TestUtils». И ещё когда потом будешь делать merge (squash) тоже не забудь поправить этот заголовок, так как  он уйдёт в сообщение squash-коммита.
4. Ты назвал это рефакторингом, но у тебя тут добавляются новые классы. Это уже не рефакторинг. Выдели добавление класса в отдельную задачу и не забудь в название PR вставить название карточки над которой работаешь. Не усложняй, делай изменения атомарными. Мы не объединяем разные работы в один PR.
5. Ну и как уже говорил, если переделываешь базовые утилиты, то исправляй сразу все места где они используются, иначе ты не улучшаешь, а ломаешь проект. В описании PR последующего коммита добавь комментарий о сути изменений, чтобы другие поняли как их использовать правильно.

2021-06-02 23:59 UTC, closed without merging

2021-06-03 00:00 UTC, Wis13 commented
Create new PR