Vk/test placeholder
SergeiDemyanenko/PlatformaticaQA_02 pull request #241
Opened 2021-05-28 16:06 UTC by korikuman

Add new test for User story 046 - testPlaceholderDeleteRecordPermanently
https://trello.com/c/xxXGrz0n

2021-05-28 18:45 UTC, SergeiKuznetsov requested changes

2021-05-28 18:45 UTC, SergeiKuznetsov commented on src/test/java/EntityCalendarTest.java
> +
Зачем добавлять тут строку? Да ещё именно в рамках твоей задачи.

2021-05-28 18:45 UTC, SergeiKuznetsov commented on src/test/java/EntityPlaceholder.java
> +    public void testPlaceholderDeleteRecordPermanently(){
```suggestion
    public void testPlaceholderDeleteRecordPermanently() {
```

2021-05-28 18:45 UTC, SergeiKuznetsov commented on src/test/java/EntityPlaceholder.java
> +
```suggestion
```

2021-05-28 18:45 UTC, SergeiKuznetsov commented on src/test/java/EntityPlaceholder.java
> +
Пустые строки перед закрывающими скобками излишни. Фигурные скобки уже визуально отделены от остального кода отступом, этого достаточно.

2021-05-28 18:45 UTC, SergeiKuznetsov commented on src/test/java/EntityPlaceholder.java
> +
```suggestion
```

2021-05-28 18:45 UTC, SergeiKuznetsov commented on src/test/java/EntityCalendar1Test.java
> +    @Ignore
Игнорить чужие тесты можно, но предварительно создав в трелло карточку с тегом `Error in code`
Вставить туда кусок лога с ошибкой и назначить автора сбойного теста ответственным за задачу. 

Если так не сделать, то никто не узнает почему тест отключен и как исправить.

2021-05-28 18:47 UTC, SergeiKuznetsov requested changes
Мы не работаем анонимно. Подписывать работу ником не есть хорошо.
[Представьтесь](https://www.notion.so/4aff35cd5e154b4b94ba149846ffab76#67a07e8e117f4addaaa0ef79cf47a107) полным именем пожалуйста.

2021-05-28 18:51 UTC, SergeiKuznetsov commented on src/test/java/EntityPlaceholder.java
> +    public void testPlaceholderDeleteRecordPermanently(){
Название функции и её реализация в блоке в фигурных скобках это две разные сущности, значит желательно разделить их пробелом, чтобы не затруднять чтение кода.

2021-05-28 22:07 UTC, Burdishka commented on src/test/java/EntityPlaceholder.java
> +public class EntityPlaceholder extends BaseTest {
забыли дописать Test в конце названия класса

EntityPlaceholderTest

2021-05-29 16:20 UTC, korikuman commented on src/test/java/EntityCalendarTest.java
> +
corrected, the line removed

2021-05-29 16:20 UTC, korikuman commented on src/test/java/EntityPlaceholder.java
> +    public void testPlaceholderDeleteRecordPermanently(){
Corrected; underscore added to separate feature and function

2021-05-29 16:21 UTC, korikuman commented on src/test/java/EntityPlaceholder.java
> +
Corrected; line removed

2021-05-29 16:22 UTC, korikuman commented on src/test/java/EntityCalendar1Test.java
> +    @Ignore
rollbacked; someone already ignored the test

2021-05-29 16:23 UTC, korikuman commented on src/test/java/EntityPlaceholder.java
> +public class EntityPlaceholder extends BaseTest {
corrected

2021-05-31 17:07 UTC, SergeiKuznetsov commented
> Мы не работаем анонимно. Подписывать работу ником не есть хорошо.
> [Представьтесь](https://www.notion.so/4aff35cd5e154b4b94ba149846ffab76#67a07e8e117f4addaaa0ef79cf47a107) полным именем пожалуйста.

На компьютере ты нормально настроил имя в Git —  Volodymyr Korenevskyy
Но [в профиле GitHub](https://www.notion.so/4aff35cd5e154b4b94ba149846ffab76#d54c7fee707e406e92c1cbbf0aafa70d) его не прописал. В результате, при слиянии, squash-коммит подпишется ником, который никто не знает. Добавь имя пожалуйста.

2021-06-02 03:46 UTC, AlekseiMaslo requested changes

2021-06-02 03:46 UTC, AlekseiMaslo commented on src/test/java/EntityPlaceholderDeleteTest.java
> +        WebDriverWait wait = new WebDriverWait(getDriver(), 10);
Этот wait есть в BaseClass и твой класс уже наследует BaseClass

2021-06-03 19:26 UTC, SergeiKuznetsov commented
@VladKorenevskyy какие-то проблемы  с донастройкой профиля GitHub? Если инструкция не понятна, скажи.

И обнови свою ветку. Подгрузи свежие коммиты из main. Может тогда и тесты не упадут

2021-06-03 19:50 UTC, SergeiKuznetsov commented
Обновил сам. Тесты прошли.

2021-06-03 22:54 UTC, AlekseiMaslo approved these changes
looks good

2021-06-03 23:04 UTC, SergeiKuznetsov approved these changes

2021-06-03 23:04 UTC, merged