Test added to GroupBugBustersTest.java - by bzhumanova My first commit to github with my first auto test! yeah!
SergeiDemyanenko/PlatformaticaQA_02 pull request #26
Opened 2021-05-10 01:10 UTC by bzhumanova

2021-05-10 01:42 UTC, LiudmilaPe reviewed
Поиск по странице выдает 11 элементов с id ="block_2-0". Может быть, стоит использовать более уникальный локатор? Сейчас код работает потому что искомый элемент первый в  списке.

2021-05-14 01:07 UTC, SergeiKuznetsov approved these changes

2021-05-14 01:08 UTC, SergeiKuznetsov requested changes

2021-05-14 01:08 UTC, SergeiKuznetsov commented on src/test/java/GroupBugBustersTest.java
> +
```suggestion
    
```

2021-05-14 01:08 UTC, SergeiKuznetsov commented on src/test/java/GroupBugBustersTest.java
> +
```suggestion
    
```

2021-05-14 06:00 UTC, SergeiKuznetsov approved these changes

2021-05-14 11:22 UTC, guram21 approved these changes

2021-05-14 16:19 UTC, merged