AG- Fix error
SergeiDemyanenko/PlatformaticaQA_02 pull request #322
Opened 2021-06-01 21:39 UTC by G-Aleksey

2021-06-02 18:32 UTC, Wis13 approved these changes
LGFM

2021-06-02 19:25 UTC, AlekseiMaslo approved these changes
Looks good

2021-06-06 03:41 UTC, SergeiKuznetsov requested changes
Пропиши нормальное название для запроса на слияние (Pull Request) и добавь ссылку на задачу в трелло.

2021-06-06 18:25 UTC, G-Aleksey commented
> Пропиши нормальное название для запроса на слияние (Pull Request) и добавь ссылку на задачу в трелло.


> Пропиши нормальное название для запроса на слияние (Pull Request) и добавь ссылку на задачу в трелло.


Спасибо! Сделал ссылку на трелло! А что не так в названии? можешь сказать @SergeiKuznetsov ? или как должно быть?

2021-06-06 18:29 UTC, SergeiKuznetsov commented
Сейчас названия нет. Это какой-то бессмысленный набор символов. А должен быть осмысленный заголовок, по которому понятно что ты предлагаешь. Для образца посмотри как делают другие и делай по подобию.

2021-06-06 18:38 UTC, G-Aleksey commented
> Пропиши нормальное название для запроса на слияние (Pull Request) и добавь ссылку на задачу в трелло.

Сделано, спасибо)

2021-06-06 20:30 UTC, G-Aleksey commented
> Сейчас названия нет. Это какой-то бессмысленный набор символов. А должен быть осмысленный заголовок, по которому понятно что ты предлагаешь. Для образца посмотри как делают другие и делай по подобию.

@SergeiKuznetsov  Сделал! Подскажи пожалуйста, почему не мержется у меня код? Уже весит 4 -й день не могу замержить!(((

2021-06-06 21:11 UTC, SergeiKuznetsov approved these changes

2021-06-06 21:17 UTC, SergeiKuznetsov commented
>  Уже весит 4 -й день не могу замержить!(((

Потому что блок стоял. Тебя попросили поправить, а ты игнорировал. Теперь я блок снял.
Обрати внимание, что **Сообщение коммита** в auto-merge тоже надо проверять на корректность. Оно автоматически не меняется при редактировании **Сообщения PR**.

2021-06-06 22:22 UTC, SergeiKuznetsov commented
Ну и желательно актуализировать ветку с main, чтобы CI проверял актуальный код, а не твой старый, с которого начинал ветку.

2021-06-06 22:31 UTC, merged