Entity > ArithmeticFunctionTest refactoting
SergeiDemyanenko/PlatformaticaQA_02 pull request #369
Opened 2021-06-04 03:58 UTC by RobinHooD1024

2021-06-05 14:08 UTC, Burdishka commented
Trello card with label refactoring?

2021-06-05 14:09 UTC, RobinHooD1024 commented
https://trello.com/c/8Gs03GT9/260-errjava-entityarithmeticfunctiontest-testeditrecord

2021-06-07 03:57 UTC, ValeriiSarukhanov commented on src/test/java/EntityArithmeticFunctionTest.java
>      private static final By CREATE_NEW = By.xpath("//i[text()='create_new_folder']");
Эта кнопка существует как:  ProjectUtils.clickCreateRecord(getDriver());

2021-06-08 19:52 UTC, RobinHooD1024 commented on src/test/java/EntityArithmeticFunctionTest.java
>      private static final By CREATE_NEW = By.xpath("//i[text()='create_new_folder']");
исправил. это был чужой код, я звал автора сделать рефакторинг, пришлось сделать самому.

2021-06-08 22:23 UTC, ValeriiSarukhanov approved these changes

2021-06-09 02:07 UTC, guram21 requested changes
Please create a refactoring card in Trello and attach it to this pull request.

2021-06-09 02:10 UTC, RobinHooD1024 commented
@guram21 выше есть карточка на ERROR
https://trello.com/c/8Gs03GT9/260-errjava-entityarithmeticfunctiontest-testeditrecord
надо создавать дополнительную на рефакторинг, если я исправляю ошибку чтобы снять Ignore?

2021-06-09 02:22 UTC, guram21 approved these changes

2021-06-09 02:22 UTC, merged

2021-06-09 02:23 UTC, guram21 commented
> @guram21 выше есть карточка на ERROR
> https://trello.com/c/8Gs03GT9/260-errjava-entityarithmeticfunctiontest-testeditrecord
> надо создавать дополнительную на рефакторинг, если я исправляю ошибку чтобы снять Ignore?

You good!

2021-06-09 02:25 UTC, RobinHooD1024 commented
Thanks, next time I'll put the link to Trello in the first comment.