refactoring EntityDefaultTest:testCreateNewRecordAsDraft
SergeiDemyanenko/PlatformaticaQA_02 pull request #378
Opened 2021-06-05 01:01 UTC by ponomid

2021-06-05 02:13 UTC, Burdishka commented on src/test/java/EntityDefaultTest.java
> +        String expectedDatetimeString = expectedDatetime.getAttribute("value");
в этом тесте вы дублируете код - вы тут создаете локаторы, которые уже есть вначале класса. Повторю, у вас все локаторы уже обьявлены вначале класса.
Так же у вас этот тест всегда будет проходить, вы сравниваете постоянно два значения которые достаете из одного и того же локатора, например:

Assert.assertEquals(expectedStringString, string);
Где expectedStringString = expectedString.getAttribute("value"), expectedString = findElement(STRING_FIELD), By STRING_FIELD = By.id("string") ======= string = findElement(By.id("string")).getAttribute("value")

У вас везде сравнивается что-то само с собой. Это 100% проходимый тест.

Вам нужно сравнивать актуальный результат с ожидаемым. Создайте лист с ожидаемым результатом и сравнивайте актуальный результат после создания с ожидаемым, который вы знаете до того как создаете запись. Только дату и время можете добавлять в лист (брать из полей перед созданием) или не проверять их вообще после создания.

2021-06-05 02:16 UTC, Jenny-ai approved these changes
lgtm

2021-06-05 13:57 UTC, SergeiDemyanenko requested changes

2021-06-05 13:57 UTC, SergeiDemyanenko commented on src/test/java/EntityDefaultTest.java
> +        Assert.assertFalse(string.isEmpty());
Все assert должны быть в конце теста

2021-06-05 13:57 UTC, SergeiDemyanenko commented on src/test/java/EntityDefaultTest.java
>          String string = findElement(By.id("string")).getAttribute("value");
Тут стоит использовать локатор STRING_FIELD и для остальных тоже есть заготовленные локаторы

2021-06-06 00:07 UTC, ponomid commented on src/test/java/EntityDefaultTest.java
> +        String expectedDatetimeString = expectedDatetime.getAttribute("value");
Got it, thank you! I fixed

2021-06-06 00:07 UTC, ponomid commented on src/test/java/EntityDefaultTest.java
> +        Assert.assertFalse(string.isEmpty());
Done!

2021-06-06 00:08 UTC, ponomid commented on src/test/java/EntityDefaultTest.java
>          String string = findElement(By.id("string")).getAttribute("value");
Fixed!

2021-06-06 00:15 UTC, closed without merging