AT_099_Java | Entity > Import: Create new record
SergeiDemyanenko/PlatformaticaQA_02 pull request #420
Opened 2021-06-08 18:18 UTC by AntonBrut

Add class EntityImportNewRecordTest and test testCreateNewRecord

2021-06-09 04:12 UTC, ValeriiSarukhanov commented
Один PR - один Тест.

2021-06-09 04:13 UTC, ValeriiSarukhanov commented
Нет ссылки на Трелло

2021-06-09 04:17 UTC, ValeriiSarukhanov requested changes

2021-06-09 04:17 UTC, ValeriiSarukhanov commented on src/test/java/EntityChildRecordsLoopTest.java
> +    public void testDeletePermanentlyChildRecordsLoopCard() {
Один PR - один Тест.
Нельзя в одном PR постить несколько тестов.

2021-06-09 04:17 UTC, ValeriiSarukhanov commented on src/test/java/EntityArithmeticFunctionTest.java
> +        ProjectUtils.clickSave(getDriver());
Мы не делаем одновременный рефактор и новый тест в одном PR

2021-06-09 05:00 UTC, AntonBrut commented on src/test/java/EntityChildRecordsLoopTest.java
> +    public void testDeletePermanentlyChildRecordsLoopCard() {
Это merge to current ветки main в мою ветку

2021-06-09 05:04 UTC, AntonBrut commented on src/test/java/EntityArithmeticFunctionTest.java
> +        ProjectUtils.clickSave(getDriver());
Это не мой тест, это обновления из ветки main

2021-06-09 05:22 UTC, ValeriiSarukhanov commented on src/test/java/EntityChildRecordsLoopTest.java
> +    public void testDeletePermanentlyChildRecordsLoopCard() {
Спроси у Сергея Кузнецова что делать в этой ситуации.
Других тестов быть не должно.

2021-06-09 05:23 UTC, ValeriiSarukhanov commented on src/test/java/EntityArithmeticFunctionTest.java
> +        ProjectUtils.clickSave(getDriver());
Узнай у Сергея Кузнецова, что делать.
Если это не твоё, то и ПР его не должно быть

2021-06-09 05:28 UTC, AntonBrut commented on src/test/java/EntityChildRecordsLoopTest.java
> +    public void testDeletePermanentlyChildRecordsLoopCard() {
Понял, благодарю за комментарии!

2021-06-09 07:01 UTC, SergeiKuznetsov commented
@ValeriiSarukhanov  Косяки с синхронизацией с main поправили. Сейчас выглядит неплохо. 
Я так и не понял как так получилось, но починил.

2021-06-09 13:42 UTC, ValeriiSarukhanov commented
@SergeiKuznetsov большое спасибо.

2021-06-09 17:12 UTC, ValeriiSarukhanov commented on src/test/java/EntityImportNewRecordTest.java
> +
Никак не могу найти способ входа на website.
Как вы туда вошли?

2021-06-09 17:12 UTC, ValeriiSarukhanov commented on src/test/java/EntityImportNewRecordTest.java
> +        TestUtils.scrollClick(getDriver(), By.xpath("//button[@data-table_id='22']"));
Вторая запись вам не нужна

2021-06-09 19:33 UTC, AntonBrut commented on src/test/java/EntityImportNewRecordTest.java
> +
В методе BaseTest.beforeMethod() (аннотация @BeforeMethod) вызывается ProjectLogin.start(getDriver())

2021-06-09 19:39 UTC, AntonBrut commented on src/test/java/EntityImportNewRecordTest.java
> +        TestUtils.scrollClick(getDriver(), By.xpath("//button[@data-table_id='22']"));
@ValeriiSarukhanov Я связывался с автором user story по вопросу проверки полей -  нужно ли мне проверять правильность всех полей (верхняя таблица и нижняя таблица). В итоге пришли к выводу - проверять все поля, соответственно нужно создавать все

2021-06-09 19:46 UTC, ValeriiSarukhanov commented on src/test/java/EntityImportNewRecordTest.java
> +
Да, конечно.

2021-06-09 19:47 UTC, ValeriiSarukhanov commented on src/test/java/EntityImportNewRecordTest.java
> +        TestUtils.scrollClick(getDriver(), By.xpath("//button[@data-table_id='22']"));
Хорошо.
Тогда попросите переписать user story.

2021-06-09 19:48 UTC, ValeriiSarukhanov commented
ok

2021-06-09 19:48 UTC, ValeriiSarukhanov approved these changes

2021-06-10 12:27 UTC, DudeAlex approved these changes

2021-06-10 17:48 UTC, merged