Entity > Readonly: Create draft record
SergeiDemyanenko/PlatformaticaQA_02 pull request #460
Opened 2021-06-11 14:32 UTC by NYerlan

Card will be created by Guram's team soon.
I want to check CI test for now

2021-06-11 17:47 UTC, MichaelMicrof approved these changes

2021-06-12 02:49 UTC, ValeriiSarukhanov requested changes

2021-06-12 02:49 UTC, ValeriiSarukhanov commented on src/test/java/EntityReadonlyTest.java
> +        findElement(By.id("decimal")).sendKeys("20.55");
Как ты вносишь данные в строки, если в этом Entity просто не возможно!!!

2021-06-12 02:49 UTC, ValeriiSarukhanov commented on src/test/java/EntityReadonlyTest.java
> +    private void clickSaveButton() {
Эта кнопка существует.
Просто введи ProjectUtils.clickSave(getDriver);

2021-06-12 02:49 UTC, ValeriiSarukhanov commented on src/test/java/EntityReadonlyTest.java
> +    private void clickCreateRecordButton() {
ProjectUtils.clickCreateRecord(getDriver);

2021-06-12 14:21 UTC, ValeriiSarukhanov approved these changes

2021-06-12 14:21 UTC, ValeriiSarukhanov commented on src/test/java/EntityReadonlyTest.java
> +        findElement(By.id("decimal")).sendKeys("20.55");
I read the user story one more time. 
Ok

2021-06-12 15:05 UTC, merged