Vk entity tag view
SergeiDemyanenko/PlatformaticaQA_02 pull request #498
Opened 2021-06-14 19:25 UTC by Wis13

Refactoring Test Entity Tag View
[Trello](https://trello.com/c/dfh1a9Mp/193-tc024-entity-tag-view-record)

2021-06-14 19:59 UTC, MichaelMicrof requested changes
Это EntityTag или EntityArifmeticFunction?

2021-06-14 20:44 UTC, MariaMoroz approved these changes

2021-06-15 00:43 UTC, ValeriiSarukhanov approved these changes

2021-06-15 01:10 UTC, MichaelMicrof approved these changes

2021-06-15 01:10 UTC, merged