Add test view record to entity Tag
SergeiDemyanenko/PlatformaticaQA_02 pull request #499
Opened 2021-06-14 19:41 UTC by Wis13

Add depended test view record to entity Tag
[Trello](https://trello.com/c/k7Nodjua/103-us024-entity-tag-view-record)

2021-06-14 20:00 UTC, MichaelMicrof requested changes
Это EntityTag или EntityArifmeticFunction?

2021-06-14 20:07 UTC, MariaMoroz commented
У Вас прикреплена карточка US, а нужно на AT и в том случае, если Вы создаете новый класс с тестом. А как я понимаю, Вы делаете рефакторинг существующего класса с добавлением теста. Для этого нужна карточка RF. И еще момент, если Вы затрагиваете чужие тесты, то нужно сначала обговорить все с авторами тестов и потом при создании карточки RF, добавить всех авторов в нее.(Посмотрите сегодняшнюю переписку в канале Java по подобным вопросам)

2021-06-14 21:47 UTC, MariaMoroz approved these changes

2021-06-14 23:34 UTC, Wis13 commented
> Это EntityTag или EntityArifmeticFunction?

Это EntityTag!! EntityArifmeticFunction был добавлен случайно и уже удален!

2021-06-15 01:06 UTC, ValeriiSarukhanov approved these changes

2021-06-15 01:11 UTC, MichaelMicrof approved these changes

2021-06-15 23:14 UTC, merged