EntityTagAssignTest refactoredd
SergeiDemyanenko/PlatformaticaQA_02 pull request #505
Opened 2021-06-15 01:37 UTC by BELOVEZHIE

2021-06-15 15:05 UTC, MariaMoroz reviewed
Нужно оформить правильно карточки в трелло. И присоединить к данному PR

2021-06-15 15:31 UTC, ValeriiSarukhanov commented
Где ссылка на трелло?
Если убрал игнор, то убери импорт игнор.
Каким образом код будет работать лучше, если он не изменен?
Снятие игнора не гарантирует стабильности работы теста.

2021-06-15 20:21 UTC, ArinaJur requested changes
Could you please add a link to the task and to the user story? It is necessary.

2021-06-16 13:58 UTC, Jenny-ai commented
Я просмотрела код м вижу у вас множество xpath неустойчивых. Вам нужна помощь?

2021-07-02 19:38 UTC, closed without merging

2021-07-02 19:38 UTC, MichaelMicrof commented
There isn't work on this PR for more than 2 weeks.