AT_057 | Entity > Default: testEditRecord
SergeiDemyanenko/PlatformaticaQA_02 pull request #544
Opened 2021-06-16 21:02 UTC by Staschampion

AT https://trello.com/c/4csU6wlY/931-at155-entity-default-testeditrecord

2021-06-17 19:56 UTC, MichaelMicrof requested changes
Where is your TC? Why your AT wasn't connected with US? Why did you create this method in separate file? Is this duplicate?

2021-06-17 19:57 UTC, MichaelMicrof commented on src/test/java/EntityDefaultEditRecordTest.java
> +        findElement(By.xpath("//i[contains(text(), 'create_new_folder')] ")).click();
we have special method for this

2021-06-17 19:58 UTC, MichaelMicrof commented on src/test/java/EntityDefaultEditRecordTest.java
> +        findElement(By.id("pa-entity-form-save-btn")).click();
the same

2021-06-17 19:58 UTC, MichaelMicrof commented on src/test/java/EntityDefaultEditRecordTest.java
> +        TestUtils.scrollClick(getDriver(), getDriver().findElement(By.xpath("//p[contains(text(), 'Default')] ")));
and this

2021-06-17 19:58 UTC, MichaelMicrof commented on src/test/java/EntityDefaultEditRecordTest.java
> +        findElement(By.xpath("//button/i[text()='menu']")).click();
and this

2021-06-17 19:59 UTC, MichaelMicrof commented on src/test/java/EntityDefaultEditRecordTest.java
> +        stringField.click();
why did you need this lines?

2021-06-17 20:00 UTC, MichaelMicrof commented on src/test/java/EntityDefaultEditRecordTest.java
> +        TestUtils.jsClick(getDriver(), findElement(By.id("pa-entity-form-save-btn")));
we have special method for this

2021-06-18 00:10 UTC, Staschampion commented on src/test/java/EntityDefaultEditRecordTest.java
> +        findElement(By.id("pa-entity-form-save-btn")).click();
no need for me

2021-06-18 00:10 UTC, Staschampion commented on src/test/java/EntityDefaultEditRecordTest.java
> +        findElement(By.xpath("//i[contains(text(), 'create_new_folder')] ")).click();
no need for me

2021-06-18 00:20 UTC, Staschampion reviewed
as for me there the line absolutely does not interfere there two actions

2021-06-18 00:20 UTC, Staschampion commented on src/test/java/EntityDefaultEditRecordTest.java
> +        stringField.click();
which one?

2021-06-18 03:00 UTC, MichaelMicrof commented on src/test/java/EntityDefaultEditRecordTest.java
> +        stringField.click();
why did you use line 41? For what?

2021-06-20 22:58 UTC, Staschampion commented on src/test/java/EntityDefaultEditRecordTest.java
> +        stringField.click();
I need click on line for make change!

2021-07-02 19:40 UTC, MichaelMicrof commented
There isn't work on this PR for more than 2 weeks.

2021-07-03 19:09 UTC, MichaelMicrof commented
Stas, I have already explained to you more than once that in order for your PR to pass, you must at least make corrections to your Trello card. What changes are needed - I also wrote to you. It will take 30 seconds, you have been pushing for the third week. If you don't want to follow the rules, it's up to you. When you do everything right, you can get your PR out of the closed ones again. Until then, don't clutter up the list !!!

2021-07-03 21:30 UTC, Staschampion commented
Да откройте трелло !!! Там всё есть и не трогайте мой код!!! Не не лезьте ко мне!!!

2021-07-06 15:27 UTC, ArinaJur approved these changes
Approve

2021-07-06 15:30 UTC, Staschampion commented
> Where is your TC? Why your AT wasn't connected with US? Why did you create this method in separate file? Is this duplicate?

TC added please check changes

2021-07-06 19:23 UTC, MichaelMicrof approved these changes

2021-07-06 19:23 UTC, merged