VictoriiaM. HomeWork: Check item Name on the Target page
SergeiDemyanenko/PlatformaticaQA_02 pull request #55
Opened 2021-05-11 02:53 UTC by VictoriaMarushevska

2021-05-11 10:28 UTC, sergeonevdah requested changes
Можешь написать другие xPath?

2021-05-11 10:28 UTC, sergeonevdah commented on src/test/java/ViktoriiaMarushevskaTest.java
> +        WebElement choiceItem = driver.findElement(By.xpath("//*[@id=\"mainContainer\"]/div[4]/div[2]/div/div[2]/div[3]/div[2]/ul/li[2]/div/div[2]/div/div/div/div[1]/div[1]/a"));
что это за элемент?

2021-05-11 20:25 UTC, VictoriaMarushevska commented on src/test/java/ViktoriiaMarushevskaTest.java
> +        WebElement choiceItem = driver.findElement(By.xpath("//*[@id=\"mainContainer\"]/div[4]/div[2]/div/div[2]/div[3]/div[2]/ul/li[2]/div/div[2]/div/div/div/div[1]/div[1]/a"));
Элемент: гипер текст товара, который я выбрала из полученных результатов поиска по названию товара.  Т.к.  у этого элемента "Assorted Sizes Flexible Fabric Bandages - 30ct - up & up™"  в коде страницы отсутствует id, поиск по классу выбирает 6 элементов, а поиск по XPath находит один элемент, то я применила поиск XPath

2021-05-11 20:38 UTC, VictoriaMarushevska commented on src/test/java/ViktoriiaMarushevskaTest.java
> +        WebElement choiceItem = driver.findElement(By.xpath("//*[@id=\"mainContainer\"]/div[4]/div[2]/div/div[2]/div[3]/div[2]/ul/li[2]/div/div[2]/div/div/div/div[1]/div[1]/a"));
Другой  ХPath пока не могу написать

2021-05-11 21:18 UTC, sergeonevdah commented on src/test/java/ViktoriiaMarushevskaTest.java
> +        WebElement choiceItem = driver.findElement(By.xpath("//*[@id=\"mainContainer\"]/div[4]/div[2]/div/div[2]/div[3]/div[2]/ul/li[2]/div/div[2]/div/div/div/div[1]/div[1]/a"));
или
//a[contains(text(),'Assorted Sizes Flexible Fabric Bandages - 30ct - up & up™']

2021-05-12 00:02 UTC, VictoriaMarushevska commented on src/test/java/ViktoriiaMarushevskaTest.java
> +        WebElement choiceItem = driver.findElement(By.xpath("//*[@id=\"mainContainer\"]/div[4]/div[2]/div/div[2]/div[3]/div[2]/ul/li[2]/div/div[2]/div/div/div/div[1]/div[1]/a"));
К сожалению, предложенные вами XPath не работали. Я поняла направление, спасибо. Код изменён

2021-05-12 21:14 UTC, sergeonevdah approved these changes
LGFM

2021-05-13 00:55 UTC, SergeiKuznetsov requested changes
А можно было добавить свой тест в любую группу

2021-05-13 00:55 UTC, SergeiKuznetsov commented on src/test/java/ViktoriiaMarushevskaTest.java
> +    private WebDriver driver;
```suggestion

    private WebDriver driver;
```

2021-05-13 00:55 UTC, SergeiKuznetsov commented on src/test/java/ViktoriiaMarushevskaTest.java
> +
```suggestion
```

2021-05-13 01:14 UTC, VictoriaMarushevska commented on src/test/java/ViktoriiaMarushevskaTest.java
> +    private WebDriver driver;
Хочется всё делать осознанно и понимать к какой группе отношусь, быть в камьюнити, а не для галочки отправить в любую группу.  Я писала и озвучивала на ревью этот вопрос, пока нет ответа от тим лида Olga Anis и жду ответ от Антона.

2021-05-13 01:24 UTC, SergeiKuznetsov commented on src/test/java/ViktoriiaMarushevskaTest.java
> +    private WebDriver driver;
А я думал хочется научиться работать в команде)

Поправь эти ошибки тогда.

2021-05-13 22:02 UTC, VictoriaMarushevska commented on src/test/java/ViktoriiaMarushevskaTest.java
> +    private WebDriver driver;
Да, хочется учиться работать в команде. Предложенные изменения - применила. Класс переименовала под название группы, может кто-то добавится. Можно где-то почитать про форматирование в Java?

2021-05-13 22:24 UTC, SergeiKuznetsov approved these changes

2021-05-13 23:16 UTC, merged