Mike kamentsev entity fields draft test
SergeiDemyanenko/PlatformaticaQA_02 pull request #563
Opened 2021-06-17 22:27 UTC by mkament

Added 5 test for Platformatica Entity: Fields. 
Trello tickets AT_136, AT_137, AT_138, AT_139, and AT_140.

2021-06-18 01:42 UTC, Asalot approved these changes

2021-06-18 23:42 UTC, MariaMoroz requested changes
Один PR = одной задаче. У Вас же целых 5. Должно быть 5 PRs. И еще, надо ссылку на карточку из трелло прикладывать, а не просто написать номер

2021-06-21 04:08 UTC, Jenny-ai approved these changes
на Trello link прикрипите

2021-06-22 05:13 UTC, mkament commented
на Trello links  прикрипил: AT_136, AT_137, AT_138, AT_139, & AT_140.

2021-06-22 05:17 UTC, MariaMoroz approved these changes

2021-06-22 05:23 UTC, merged