AT_184 | Entity > Reference Values: Delete the record from the Recycle Bin permanently
SergeiDemyanenko/PlatformaticaQA_02 pull request #564
Opened 2021-06-18 01:22 UTC by Asalot

US_184 | Entity > Reference Values: Delete the record from the Recycle Bin permanently
https://trello.com/c/euRPRTwx/874-us184-entity-reference-values-delete-the-record-from-the-recycle-bin-permanently

AT_184 | Entity > Reference Values: Delete the record from the Recycle Bin permanently
https://trello.com/c/bgPGE2xy/960-at184-entity-reference-values-delete-the-record-from-the-recycle-bin-permanently

2021-06-18 22:07 UTC, mkament reviewed
Clever code. Streams look neat! Good job! At 185 lines lines 31 to 36 should be condensed into 3 lines to keep the code more compact without redundant carryovers. SergeyD was saying that verications in a loop are time intensive thus should be avoided on lines 49 or 51, etc (IMHO) . Some locators like on line 145 are huge giants (did I mention they are big? :) I think they can possibly be simplified into expressions of diminished length.  Sorry I did not fully grasp why "OriginalValueOfDeletedRecords--;" statement is utilized but it does take many lines. Please fix lines 31 to 36  so that I can greenlight the code and you can merge it. Your work is truly inspiring! Fantastic effort with immense skill and tremendous execution. A+

2021-06-18 22:08 UTC, mkament requested changes
Clever code. Streams look neat! Good job! At 185 lines lines 31 to 36 should be condensed into 3 lines to keep the code more compact without redundant carryovers. SergeyD was saying that verications in a loop are time intensive thus should be avoided on lines 49 or 51, etc (IMHO) . Some locators like on line 145 are huge giants (did I mention they are big? :) I think they can possibly be simplified into expressions of diminished length. Sorry I did not fully grasp why "OriginalValueOfDeletedRecords--;" statement is utilized but it does take many lines. Please fix lines 31 to 36 so that I can greenlight the code and you can merge it. Your work is truly inspiring! Fantastic effort with immense skill and tremendous execution. A+

2021-06-18 23:29 UTC, mkament approved these changes

2021-06-18 23:57 UTC, mkament commented
Trello teickets automated:
https://trello.com/c/SRJiCl32/651-at136java-entity-fields-create-a-draft-record
https://trello.com/c/WraPC8A3/658-at137java-entity-fields-view-draft-record
https://trello.com/c/MVS6q7Pq/669-at139java-entity-fields-delete-draft-record
https://trello.com/c/4PhIbmvL/688-at140java-entity-fields-delete-permanently-draft-record-from-recycle-bin

2021-06-19 06:23 UTC, ValeriiSarukhanov approved these changes

2021-06-19 15:22 UTC, merged