RF | POM - EntityReadonlyTest
SergeiDemyanenko/PlatformaticaQA_02 pull request #577
Opened 2021-06-19 06:04 UTC by NYerlan

https://trello.com/c/I0PL4XMB/1002-rf-pom-entityreadonlytest

2021-06-19 14:20 UTC, BELOVEZHIE approved these changes

2021-06-19 18:59 UTC, skhat requested changes

2021-06-19 18:59 UTC, skhat commented on src/test/java/EntityReadonlyTest.java
> +                .clickReadonlyMenu();
А где метод просмотр draft записи? Надо кликнуть и просмотреть запись.

2021-06-23 17:57 UTC, skhat approved these changes

2021-06-23 17:59 UTC, merged