Test Lena D
SergeiDemyanenko/PlatformaticaQA_02 pull request #60
Opened 2021-05-11 05:09 UTC by LenaDik

Test https://www.lafitness.com/

2021-05-11 05:20 UTC, Lizzzzi approved these changes
agree!

2021-05-11 05:23 UTC, valdisone approved these changes
LGFM

2021-05-11 06:30 UTC, guram21 requested changes

2021-05-11 06:30 UTC, guram21 commented on src/test/java/GroupBreakingBadJavaTest.java
> +    public void lenaDikTest(){
All methods with `@Test` annotation shall start with the prefix `test`.
`testLenaDik()`

2021-05-11 13:06 UTC, LenaDik commented on src/test/java/GroupBreakingBadJavaTest.java
> +    public void lenaDikTest(){
fixed, please check!

2021-05-12 01:27 UTC, guram21 approved these changes

2021-05-12 01:32 UTC, merged

2021-05-12 01:37 UTC, SergeiKuznetsov commented on src/test/java/GroupBreakingBadJavaTest.java
> +}
@guram21 последнюю строку зря удалили