EntityFieldsViewCreatedRecordTest conversion to POM.
SergeiDemyanenko/PlatformaticaQA_02 pull request #628
Opened 2021-06-25 05:52 UTC by biromsoft

FieldsPage addon posted in order for EntityFieldsViewCreatedRecordTest to work
+class rename

2021-06-25 05:54 UTC, zorganpro approved these changes
\_(ツ)_/¯

2021-06-25 16:13 UTC, ValeriiSarukhanov commented
ссылка на трелло?

2021-06-25 16:24 UTC, ValeriiSarukhanov requested changes

2021-06-25 16:24 UTC, ValeriiSarukhanov commented on src/test/java/model/FieldsPage.java
> +        getWait().until(ExpectedConditions.elementToBeClickable(
Что у вас тут происходит?
Вам нужно просто нажать на view.
Вы пользуетесь страничкой Fields - там прописан локатор для кнопки Actions - вы на нее просто кликните.
Вам останеться только прописать локатор для view и кликнуть на него,
Итого во всем методе - две строки!

2021-06-25 16:24 UTC, ValeriiSarukhanov commented on src/test/java/EntityFieldsViewCreatedRecordTest.java
> +        Assert.assertTrue(res);
Вам необходимо проверить просмотренную запись по каждому элементу.

2021-06-25 16:24 UTC, ValeriiSarukhanov commented on src/test/java/EntityFieldsViewCreatedRecordTest.java
> +                .clickExactViewRecord();
У вас  тест view.
Для чего вы создаете пять записей?

2021-06-25 16:24 UTC, ValeriiSarukhanov commented on src/test/java/EntityFieldsViewCreatedRecordTest.java
> +//    private static final String TITLE_VALUE_LOOKING_FOR = getTextRandom(10);
Удалите комментированную строку

2021-06-29 02:26 UTC, biromsoft commented
> ссылка на трелло?

добавил

2021-06-29 02:40 UTC, biromsoft commented on src/test/java/model/FieldsPage.java
> +        getWait().until(ExpectedConditions.elementToBeClickable(
У нас стояла задача не просто клинуть по Actions, а кликнуть по конкретной записи, для этого мы создали этот метод -- он ищет не первый попавшийся экшен, а конкретный -- той записи, которую мы ищем.

2021-06-29 02:44 UTC, biromsoft commented on src/test/java/EntityFieldsViewCreatedRecordTest.java
> +        Assert.assertTrue(res);
тут у нас прописано два условия:
мы проверяем, что в режиме просмотра (view) мы оказались в записи "besttextever" и одновременно с этим проверяем чтобы не было слова "showing" -- ибо только при таких условиях мы точно знаем что находимся в конкретной записи и не в списке всех записей.

2021-06-29 02:45 UTC, biromsoft commented on src/test/java/EntityFieldsViewCreatedRecordTest.java
> +                .clickExactViewRecord();
У нас стоит задача не просто просмотреть запись, а просмотреть КОНКРЕТНУЮ запись. Для этого мы создаем четыре рандомных и одну предустановленную ("besttextever"), после этого ищем КОНКРЕТНУЮ запись, а не заходим в первую попавшуюся. Возможно это как то иначе можно решить, но вот такие костыли :)

2021-06-29 02:50 UTC, biromsoft commented on src/test/java/EntityFieldsViewCreatedRecordTest.java
> +//    private static final String TITLE_VALUE_LOOKING_FOR = getTextRandom(10);
удалил

2021-06-29 03:25 UTC, ValeriiSarukhanov approved these changes

2021-06-29 03:40 UTC, merged