VladimirM
SergeiDemyanenko/PlatformaticaQA_02 pull request #63
Opened 2021-05-11 07:18 UTC by UmisTester

2021-05-11 07:20 UTC, UmisTester commented
Tasks#18

2021-05-11 07:50 UTC, SergeiKuznetsov requested changes

2021-05-11 07:50 UTC, SergeiKuznetsov commented on src/test/java/SergeiDTest.java
> +	// Test
```suggestion
```

2021-05-11 07:50 UTC, SergeiKuznetsov commented on src/test/java/SergeiDTest.java
> +	// Test
Сергей просил не трогать его класс

2021-05-11 07:50 UTC, SergeiKuznetsov commented on src/test/java/GroupAllaTest.java
> +}
```suggestion
}

```

2021-05-11 07:50 UTC, SergeiKuznetsov commented on src/test/java/GroupAllaTest.java
> +}
Не ошибка, но лучше когда последняя строка кода завершается переносом строки. 
Давай добавим?

2021-05-11 13:09 UTC, UmisTester commented on src/test/java/GroupAllaTest.java
> +}
Добавим, только как это сделать сейчас?)

2021-05-11 13:10 UTC, UmisTester commented on src/test/java/SergeiDTest.java
> +	// Test
Ок, что я должен сейчас сделать, не совсем понимаю.

2021-05-14 06:51 UTC, SergeiKuznetsov approved these changes

2021-05-14 10:57 UTC, igorchupin approved these changes
I have no questions

2021-05-14 22:45 UTC, merged

2021-05-14 22:47 UTC, SergeiKuznetsov requested changes
Не надо

2021-05-14 22:47 UTC, SergeiKuznetsov commented on src/test/java/GroupAllaTest.java
> +    public void vladimirMiskoTest() {
Забыл проверить имя метода ((

2021-05-18 19:51 UTC, UmisTester commented on src/test/java/GroupAllaTest.java
> +    public void vladimirMiskoTest() {
Поправил