AT_187 | Entity > Reference Values: View an existing record
SergeiDemyanenko/PlatformaticaQA_02 pull request #633
Opened 2021-06-25 21:32 UTC by ChuevaTatiana

add new EntityReferenceValuesViewExistingRecordTest

AT_187 https://trello.com/c/XlIuoFwi/933-at187-entity-reference-values-view-an-existing-record

2021-06-26 04:39 UTC, ValeriiSarukhanov requested changes

2021-06-26 04:39 UTC, ValeriiSarukhanov commented on src/test/java/EntityReferenceValuesViewExistingRecordTest.java
> +        Assert.assertEquals(referenceValuesPage.getRowsValue(), EXPECTED_RESULT);
У вас тест на просмотр записи через view.
У вас нет этих шагов.
Вы просто создали запись и не перешли во view mode.
А вам необходимо проверить запись именно там.

2021-06-26 21:58 UTC, ChuevaTatiana commented on src/test/java/EntityReferenceValuesViewExistingRecordTest.java
> +        Assert.assertEquals(referenceValuesPage.getRowsValue(), EXPECTED_RESULT);
я знаю.  следующий тест будет на view

2021-06-26 22:00 UTC, ChuevaTatiana commented on src/test/java/EntityReferenceValuesViewExistingRecordTest.java
> +        Assert.assertEquals(referenceValuesPage.getRowsValue(), EXPECTED_RESULT);
Я хочу следующим шагом создать класс ReferenceValuesViewPage

2021-06-26 22:10 UTC, ValeriiSarukhanov commented on src/test/java/EntityReferenceValuesViewExistingRecordTest.java
> +        Assert.assertEquals(referenceValuesPage.getRowsValue(), EXPECTED_RESULT);
Вы можете просто добавить переход на просмотр страници и проверить запись.
В этом тесте.
А в следующем ПР делайте то, что задумали.
Или измените название на создание записи, так же карточки трелло, а их там три.
Гораздо проще дописать тест, он у вас не закончен.

2021-06-27 02:57 UTC, ChuevaTatiana commented on src/test/java/EntityReferenceValuesViewExistingRecordTest.java
> +        Assert.assertEquals(referenceValuesPage.getRowsValue(), EXPECTED_RESULT);
Хорошо. Спасибо!

2021-06-27 20:10 UTC, Jenny-ai approved these changes

2021-06-30 02:19 UTC, guram21 approved these changes

2021-06-30 04:58 UTC, ValeriiSarukhanov approved these changes

2021-07-02 19:45 UTC, merged