Entity import test search
SergeiDemyanenko/PlatformaticaQA_02 pull request #641
Opened 2021-06-26 23:02 UTC by EvgeniyaPiskunova

US
https://trello.com/c/5KbXokZ0/920-us194-entity-import-values-search-created-record

TC
https://trello.com/c/3XOYqWnk/1058-tc194-entity-import-values-search-created-record

AT
https://trello.com/c/ClP97Aym/1074-at194-entity-import-values-search-created-record

2021-06-27 15:55 UTC, MariaMoroz commented on src/test/java/EntityImportCreateNewRecordTest.java
> +
Зачем Вам sleep? Почему нельзя заменить на getWait()?

2021-06-27 15:56 UTC, MariaMoroz commented on src/test/java/EntityImportCreateNewRecordTest.java
> +
нужно удалить такое огромное количество лишних строк : 157-197 строки

2021-06-28 03:43 UTC, ValeriiSarukhanov requested changes

2021-06-28 03:43 UTC, ValeriiSarukhanov commented on src/test/java/EntityImportCreateNewRecordTest.java
> +                .stream()
Для чего вам стрим?
Можно обойтись без него!

2021-06-28 03:43 UTC, ValeriiSarukhanov commented on src/test/java/EntityImportCreateNewRecordTest.java
> +
Удалите слип!!!
Он здесь не нужен!!!

2021-06-28 14:50 UTC, MariaMoroz approved these changes

2021-06-28 15:13 UTC, SergeiDemyanenko commented on src/test/java/EntityImportCreateNewRecordTest.java
> +                .stream()
@ValeriiSarukhanov Как сделать такое преобразование лучше, без стрима?

2021-06-28 15:27 UTC, ValeriiSarukhanov commented on src/test/java/EntityImportCreateNewRecordTest.java
> +                .stream()
@SergeiDemyanenko Мы создали Класс BasePage он наследуется от MainPage.
В новый класс мы положили те методы, которые повторяются но всех классах, в том числе и стрим.
Наследуемся от BasePage, и все методы в нашем распоряжении и не надо создовать стрим на каждый тест.
Все это я вчера объяснял в зуме автору теста.
В итоге это вынлядит так
        FieldsPage fieldsPage = new MainPage(getDriver())
                .clickFieldsMenu()
                .searchInput(TITLE_VALUE)
                .findInfoText(INFO_TEXT);

        Assert.assertEquals(fieldsPage.getRow(0), EXPECTED_RESULT);
        Assert.assertEquals(fieldsPage.getClassIcon(), ICON);
    }

2021-06-28 17:13 UTC, olhakovtun approved these changes

2021-06-29 02:38 UTC, ValeriiSarukhanov approved these changes

2021-06-29 04:18 UTC, merged