Dima Stepanenko first test
SergeiDemyanenko/PlatformaticaQA_02 pull request #70
Opened 2021-05-11 20:39 UTC by dmytrostepanenko

2021-05-11 21:05 UTC, Wis13 commented
Не работает поиск этого span 
 WebElement total = driver.findElement(
                By.xpath("//td[@class=\"subtotal nobr end\"]/span[@class=\"product-subtotal\"]"));
Test failed

2021-05-11 23:08 UTC, korikuman approved these changes

2021-05-12 01:33 UTC, Asalot approved these changes
Default Suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0

2021-05-12 01:41 UTC, SergeiKuznetsov requested changes

2021-05-12 01:41 UTC, SergeiKuznetsov commented on src/test/java/GroupRunSuccess.java
> +
Удали эту пустую строку

2021-05-12 04:26 UTC, dmytrostepanenko commented
@Wis13 
toString() использовал, так total.getText() выдает 48.00, а число выводится как 48.0.

Реализовал по другому: 
Assert.assertEquals(total.getText(), String.format("%.2f", 48.0));

Касательно того, что не находит элемент. Проверял много раз у меня находит и работает. 
Добавил sleep. Возможно в этом причина.

Спасибо!

2021-05-12 04:26 UTC, dmytrostepanenko commented on src/test/java/GroupRunSuccess.java
> +
Удалил, спасибо!

2021-05-12 04:34 UTC, dmytrostepanenko commented
@Wis13 @SergeiKuznetsov Посмотрите, пожалуйста, изменения. И, если все ОК, то апрувните.
Спасибо!

2021-05-12 04:37 UTC, SergeiKuznetsov approved these changes

2021-05-12 04:39 UTC, merged