Test for site akniga.org
SergeiDemyanenko/PlatformaticaQA_02 pull request #72
Opened 2021-05-11 22:09 UTC by Asalot

Hello.
There is a test for site akniga.org according HW#18

2021-05-12 06:43 UTC, SergeiKuznetsov requested changes

2021-05-12 06:43 UTC, SergeiKuznetsov commented on src/test/java/GroupStepInJavaTeamTest.java
> +    @Test
```suggestion

    @Test
```

2021-05-12 06:43 UTC, SergeiKuznetsov commented on src/test/java/GroupStepInJavaTeamTest.java
> +        WebDriverManager.chromedriver().setup();
```suggestion
```

2021-05-12 06:43 UTC, SergeiKuznetsov commented on src/test/java/GroupStepInJavaTeamTest.java
> +        WebDriverManager.chromedriver().setup();
Это уже делается в другом методе

2021-05-12 06:43 UTC, SergeiKuznetsov commented on src/test/java/GroupStepInJavaTeamTest.java
> +        WebDriver driver = new ChromeDriver();
```suggestion
```

2021-05-12 06:43 UTC, SergeiKuznetsov commented on src/test/java/GroupStepInJavaTeamTest.java
> +        WebDriver driver = new ChromeDriver();
Зачем нам переопределять переменную класса внутри метода?

2021-05-12 06:43 UTC, SergeiKuznetsov commented on src/test/java/GroupStepInJavaTeamTest.java
> +            //Verify if Category was chosen correctly
Подробное описание теста можно вынести в сообщение коммита, а не в комментарии.

2021-05-12 06:43 UTC, SergeiKuznetsov commented on src/test/java/GroupStepInJavaTeamTest.java
> +        }finally {
```suggestion
        } finally {
```

2021-05-12 06:49 UTC, SergeiKuznetsov commented
Комментарии в коде могут устареть.

Подобным примечаниям место в сообщении коммита. Можешь описать суть теста там.
[Как писать хорошие сообщения коммитов](https://techrocks.ru/2019/12/02/writing-good-commit-messages/)

2021-05-13 04:22 UTC, Asalot commented
I did my best to correct my code.

2021-05-14 06:35 UTC, SergeiKuznetsov approved these changes

2021-05-19 15:16 UTC, SergeiDemyanenko approved these changes

2021-05-20 01:09 UTC, merged