US_071 | Entity > Arithmetic Function: Edit an existing record
SergeiDemyanenko/PlatformaticaQA_02 pull request #723
Opened 2021-07-07 01:12 UTC by Wis13

Add testEditRecord
[Trello](https://trello.com/c/nYINH42t/1201-at07102java-entity-arithmetic-function-edit-an-existing-record)

2021-07-07 19:08 UTC, MariaMoroz commented on src/test/java/EntityArithmeticFunctionWorkTest.java
> +    private Integer SUM_EDIT = F1_EDIT + F2_EDIT;
немного странный способ генерации случайного десятичного числа.

2021-07-07 19:08 UTC, MariaMoroz approved these changes

2021-07-07 20:11 UTC, ValeriiSarukhanov requested changes

2021-07-07 20:11 UTC, ValeriiSarukhanov commented on src/test/java/EntityArithmeticFunctionWorkTest.java
> +    private Integer F1_EDIT = (int)Math.round(rangeMin + (rangeMax - rangeMin) * random.nextDouble());
Объясни, пожалуйста, как это работает? 
Здесь и в остальных местах, где встречается что-то похожее.

2021-07-07 21:17 UTC, Wis13 commented
Это вводит рандомные десятичные числа от0 до 100 округляет их, и выполняет с ними действия, затем округляет DIV после этого преобразует все числа в String

Sent from my iPhone

On Jul 7, 2021, at 1:12 PM, ValeriiSarukhanov ***@***.***> wrote:

﻿

@ValeriiSarukhanov requested changes on this pull request.

________________________________

In src/test/java/EntityArithmeticFunctionWorkTest.java<https://github.com/SergeiDemyanenko/PlatformaticaQA_02/pull/723#discussion_r665675320>:

>
     List<Integer> CREATE_DATA = Arrays.asList(F1, F2, SUM, SUB, MUL, DIV);
+
+    private Integer F1_EDIT = (int)Math.round(rangeMin + (rangeMax - rangeMin) * random.nextDouble());


Объясни, пожалуйста, как это работает?
Здесь и в остальных местах, где встречается что-то похожее.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/SergeiDemyanenko/PlatformaticaQA_02/pull/723#pullrequestreview-701406424>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHIS7PUMJRIG7XGW6L6L7NDTWSYJLANCNFSM475T6GPA>.

2021-07-07 22:21 UTC, ValeriiSarukhanov commented
У тебя в задаче ничего не сказано о десятичных.
Задумка интересная. 
Может новый кейс под это дело? 
Или так оставишь?

2021-07-08 15:21 UTC, ValeriiSarukhanov approved these changes

2021-07-09 20:45 UTC, merged