AT_226 | Entity > Events Chain Two: CRUD record
SergeiDemyanenko/PlatformaticaQA_02 pull request #773
Opened 2021-07-16 19:20 UTC by Wis13

[Trello](https://trello.com/c/V9T3w5WX/1266-at226-entity-events-chain-two-crud-record)

2021-07-16 19:44 UTC, MariaMoroz requested changes
Чтобы снимать игнор с теста, в коде должна быть попытка исправить ошибку.

2021-07-16 20:05 UTC, ValeriiSarukhanov commented
Карточка Trello не соответствует вашему PR.

2021-07-16 20:07 UTC, ValeriiSarukhanov requested changes

2021-07-16 20:07 UTC, ValeriiSarukhanov commented on src/test/java/EntityEventsChainTwoTest.java
> -@Ignore
Снятие Игнора без изменения кода не гарантирует исправления ошибки.
Пожалуйста, измените код!

2021-07-17 00:24 UTC, ValeriiSarukhanov approved these changes

2021-07-17 00:25 UTC, ValeriiSarukhanov commented
Что на счет карточки ТРелло?

2021-07-17 00:26 UTC, MariaMoroz approved these changes

2021-07-17 00:28 UTC, ValeriiSarukhanov requested changes

2021-07-17 00:28 UTC, ValeriiSarukhanov commented on src/test/java/EntityArithmeticFunctionTest.java
>  import base.BaseTest;
Измени карточку трелло, пожалуйста.
Она должна отброжать ошибку

2021-07-17 00:31 UTC, Wis13 commented on src/test/java/EntityArithmeticFunctionTest.java
>  import base.BaseTest;
Ok

2021-07-17 00:50 UTC, ValeriiSarukhanov approved these changes

2021-07-17 00:50 UTC, merged