Evgeniya Piskunova
SergeiDemyanenko/PlatformaticaQA_02 pull request #86
Opened 2021-05-12 03:41 UTC by EvgeniyaPiskunova

2021-05-12 06:34 UTC, SergeiKuznetsov requested changes

2021-05-12 06:34 UTC, SergeiKuznetsov commented on src/test/java/GroupStepInJavaTeamTest.java
> +    public void evgeniyaPiskunova() throws Exception {
```suggestion
    public void testEvgeniyaPiskunova() throws Exception {
```

2021-05-12 08:22 UTC, VitalyVZH commented on src/test/java/GroupStepInJavaTeamTest.java
> +    public void evgeniyaPiskunova() throws Exception {
Exception можно убрать, он в данном коде не нужен.

2021-05-14 06:33 UTC, SergeiKuznetsov commented
Пропала 😟

2021-05-14 16:31 UTC, SergeiKuznetsov commented on src/test/java/GroupStepInJavaTeamTest.java
> +    public void evgeniyaPiskunova() throws Exception {
Я предложил поменять название тут. Если нажать Commit suggestion, то создастся коммит с этой правкой прямо здесь. А у себя на компьютере потом сделай Update Project, чтобы это обновление загрузилось с GitHub к тебе в локальный репозиторий.

2021-05-14 19:06 UTC, SergeiKuznetsov approved these changes

2021-05-14 19:14 UTC, VitalyVZH approved these changes

2021-05-14 19:18 UTC, merged