Create screenshots files
SergeiDemyanenko/PlatformaticaQA_02 pull request #870
Opened 2021-08-17 19:41 UTC by Asalot

create screenshots file according to Sergei post

2021-08-17 20:33 UTC, SergeiDemyanenko requested changes

2021-08-17 20:33 UTC, SergeiDemyanenko commented on src/test/java/base/BaseUtils.java
> +
Это тут зачем? Тут специально не было пустой строки, на это есть причина.

2021-08-17 20:33 UTC, SergeiDemyanenko commented on src/test/java/base/BaseUtils.java
> +        }
Зачем эти изменения?

2021-08-17 20:33 UTC, SergeiDemyanenko commented on src/test/java/base/BaseUtils.java
> +            List<T> destinationList, Function<T, String> getNameFunction, Function<T, String[]> getDependencyFunction) {
Зачем эти изменения?

2021-08-17 20:33 UTC, SergeiDemyanenko commented on src/test/java/base/BaseUtils.java
> +            List<T> sourceList, Function<T, String> getNameFunction, Function<T, String[]> getDependencyFunction) {
Зачем эти изменения?

2021-08-17 20:33 UTC, SergeiDemyanenko commented on src/test/java/base/BaseTest.java
>          List<Method> list = BaseUtils.find(methodList, method).orElse(null);
Стоит добавить пустую строку и пробел перед this

2021-08-17 20:33 UTC, SergeiDemyanenko commented on src/test/java/base/BaseUtils.java
> +    public static void getScreenshot(WebDriver driver, String methodName, String className) {
Стоит переименовать в saveScreenshot т.к. метод ничего не возвращает.

2021-08-17 20:33 UTC, SergeiDemyanenko commented on src/test/java/base/BaseUtils.java
> +            FileUtils.copyFile(screen, new File("../ScreenshotsFailure/" +
Папка там точно есть или будет создана в этой строке?

2021-08-17 20:33 UTC, SergeiDemyanenko commented on src/test/java/base/CucumberDriver.java
>          driver.quit();
Стоит добавить пустую строку

2021-08-17 22:22 UTC, Asalot commented on src/test/java/base/BaseUtils.java
> +        }
Это не я, интелиджес сделала, когда я вставила свою функцию в конец, я resubmit последнюю скобку, чтоб подравнялся текст

2021-08-18 00:06 UTC, Asalot commented on src/test/java/base/BaseUtils.java
> +            FileUtils.copyFile(screen, new File("../ScreenshotsFailure/" +
она создаться, при первом обращении. у меня на локальной так произошло

2021-08-18 00:08 UTC, Asalot commented on src/test/java/base/CucumberDriver.java
>          driver.quit();
done

2021-08-18 12:58 UTC, SergeiDemyanenko approved these changes

2021-08-18 13:46 UTC, merged