My new test
SergeiDemyanenko/PlatformaticaQA_02 pull request #89
Opened 2021-05-12 04:03 UTC by BELOVEZHIE

2021-05-12 06:32 UTC, SergeiKuznetsov requested changes

2021-05-12 06:32 UTC, SergeiKuznetsov commented on src/test/java/AliakseiFranchukTest.java
> +
```suggestion
```

2021-05-12 06:32 UTC, SergeiKuznetsov commented on src/test/java/AliakseiFranchukTest.java
> +    public void setUpDriver(){
```suggestion
    public void setUpDriver() {
```

2021-05-13 01:43 UTC, closed without merging

2021-05-13 01:48 UTC, BELOVEZHIE commented
I deleted the file class "AliakseiFranchukTest" in my local branch. And I created it one more time, but I can`t fix it using "Refresh" with the second push. So I gonna create new PR. If it possible fix something again in there and I will resolve it as intended.