Vk  first test
SergeiDemyanenko/PlatformaticaQA_02 pull request #94
Opened 2021-05-12 05:18 UTC by valdisone

2021-05-12 06:21 UTC, SergeiKuznetsov requested changes
Убери лишний класс. Зачем он?

2021-05-12 15:31 UTC, valdisone commented
По условиям домашнего задания имя класса должно было совпадать с именем группы, я и создал этот класс. Только потом понял что нужно было запулить уже созданный. Теперь не могу никуда его деть. Я его вроде уже удалял а он всё равно где-то висит

2021-05-14 06:29 UTC, SergeiKuznetsov commented
> Я его вроде уже удалял а он всё равно где-то висит

Ты добавил класс несуществующей группы GroupBreakingBadTest.java
Удали этот файл.

2021-05-14 06:30 UTC, SergeiKuznetsov commented
Потом надо сделать merge main into current и разрешить небольшой конфликт.

2021-05-14 06:32 UTC, SergeiKuznetsov requested changes
Delete file GroupBreakingBadTest.java

2021-05-14 18:25 UTC, valdisone commented
Этот класс у меня в локале я удалил. Если я делаю пулл мейн ветки его там тоже нет. Когда Сегрей на уроке делал разбор PR-ов у него на экране я его также не наблюдал. Код который в конфликте также не содержит уже этот класс. Можешь меня ткнуть по дружески носом в место где этот класс лежит))

2021-05-14 22:39 UTC, SergeiKuznetsov commented
> Этот класс у меня в локале я удалил. 

А как ты думаешь GitHub узнает, что ты его у себя удалил? Делай коммит факта удаления и отправляй новое состояние твоей ветки (Push)

Сам [файл](https://github.com/SergeiDemyanenko/PlatformaticaQA_02/pull/94/files#diff-c421db7e4d3dacfaf98031cc3b671ad8778cd85e48954c2e4bcda62a5c9eaa65) пока есть в твоей ветке, которую ты предлагаешь слить в main

2021-05-14 22:42 UTC, SergeiKuznetsov commented
> Потом надо сделать merge main into current и разрешить небольшой конфликт.

Это тоже сделай и потом зови рецензентов.

2021-05-19 19:59 UTC, closed without merging