new test oz.by
SergeiDemyanenko/PlatformaticaQA_02 pull request #97
Opened 2021-05-12 12:00 UTC by viktoria-anatsko

2021-05-12 23:54 UTC, sergeonevdah requested changes

2021-05-12 23:54 UTC, sergeonevdah commented on pom.xml
> +            <version>7.3.0</version>
For what are these changes?

2021-05-12 23:54 UTC, sergeonevdah commented on src/test/java/ViktoriaAnatskoTest.java
> +    public void test() throws InterruptedException {
Can you update your testName? Forward #64

2021-05-13 07:03 UTC, viktoria-anatsko commented on pom.xml
> +            <version>7.3.0</version>
С версией 7.4 не получается импортировать Assert, без этого тесты не работают.

2021-05-13 12:36 UTC, viktoria-anatsko commented on src/test/java/ViktoriaAnatskoTest.java
> +    public void test() throws InterruptedException {
Спасибо. Исправила.

2021-05-19 23:40 UTC, SergeiDemyanenko commented on pom.xml
> +            <version>7.3.0</version>
Похоже, что ты что-то делаешь не так, у многих все работает на 7.4 и нет никаких проблем с импортом. В любом случае, эту версию мы используем не зря, не стоит так менять проект, он будет запускаться не у всех.

2021-05-20 01:44 UTC, SergeiKuznetsov approved these changes

2021-05-20 01:46 UTC, SergeiKuznetsov commented on pom.xml
> +            <version>7.3.0</version>
> С версией 7.4 не получается импортировать Assert, без этого тесты не работают.

@viktoria-anatsko Надо было сделать mvn clean а не ломать остальные тесты. Всё у вас работает.

2021-05-20 01:48 UTC, SergeiKuznetsov commented on pom.xml
> +            <version>7.3.0</version>
@sergeonevdah подтверди пожалуйста

2021-05-20 09:10 UTC, viktoria-anatsko commented on pom.xml
> +            <version>7.3.0</version>
Спасибо. Все ошибки из-за неопытности.
Поменяла версию на 7.4.0

2021-05-20 19:26 UTC, SergeiKuznetsov commented on pom.xml
> +            <version>7.3.0</version>
> Поменяла версию на 7.4.0

Перед тем как продолжить редактирование, всегда делайте Update Project
Ведь ветка над которой вы работаете могла измениться на сервере. Что и произошло.
И добавив коммит без обновления вы создаёте ответвление истории, вам пришлось сливать две версии в итоге.

2021-05-21 03:29 UTC, sergeonevdah approved these changes

2021-05-21 03:29 UTC, merged